projectgenerator/libili2pg/iliimporter.py
projectgenerator/qgs_project_generator.py

These 2 issues do not allow us to run the plugin.
Please let me know if you need detailed error messages.

Fixing small issues

---

projectgenerator/libili2pg/iliimporter.py
projectgenerator/libqgsprojectgen/generator/postgres/postgrescreator.py
projectgenerator/ui/generate_project.ui

+ Update ili2pg to v3.8.0
+ Fix tab order for generate_project.ui
+ Avoid printing field names (it takes time)
+ Fix SQL to get table fields

Minor fixes/updates

---

projectgenerator/gui/generate_project.py
projectgenerator/libqgsprojectgen/generator/postgres/postgrescreator.py
projectgenerator/libqgsprojectgen/generator/postgres/relations.py

Follow-up of https://github.com/opengisch/projectgenerator/pull/27

Filter relations by schema

---

projectgenerator/libili2pg/ilicache.py

This PR fixes a couple of issues we've come across when attempting to access remote model repositories.
Please see commit messages for details and let me know if something is not clear.

Fix XML parsing issues

---

projectgenerator/libqgsprojectgen/dataobjects/project.py
projectgenerator/libqgsprojectgen/generator/postgres/domain_relations.py

- Domain-class relation issue (#68)
- Hide Open Form button for enum lists (that's the only missing part to close #8)
Fix #68 
Fix #8

Fixing issues

---

projectgenerator/gui/export.py
projectgenerator/gui/generate_project.py
projectgenerator/libili2pg/ili2pg_config.py
projectgenerator/libili2pg/iliexporter.py
projectgenerator/libili2pg/iliimporter.py

Make sure custom Java path works

Fix custom Java path

---

projectgenerator/gui/generate_project.py
projectgenerator/libqgsprojectgen/dataobjects/__init__.py
projectgenerator/libqgsprojectgen/dataobjects/form.py
projectgenerator/libqgsprojectgen/dataobjects/layers.py
projectgenerator/libqgsprojectgen/dataobjects/project.py
projectgenerator/libqgsprojectgen/dataobjects/relations.py
projectgenerator/libqgsprojectgen/generator/postgres/postgrescreator.py
projectgenerator/tests/test_libili2pg.py
projectgenerator/tests/test_plugin.py
projectgenerator/tests/test_projectgen.py

References #34
A picture says more than a thousand words:

Add tabs for relations

---

projectgenerator/libili2pg/ili2pg_config.py
projectgenerator/libqgsprojectgen/generator/postgres/postgrescreator.py

+ Adjust SQL query to `t_ili2db_column_prop` with [typo fixed](https://github.com/claeis/ili2db/pull/99) in ili2pg v3.10.6

Update to ili2pg v3.10.6

---

projectgenerator/gui/import_data.py
projectgenerator/libili2pg/ili2pg_config.py
projectgenerator/libili2pg/ilidataimporter.py
projectgenerator/qgs_project_generator.py
projectgenerator/ui/import_data.ui

Add 'Import Data' option (from XTF to database)
Fix #17

Import from XTF

---

projectgenerator/gui/import_data.py
projectgenerator/qgs_project_generator.py
projectgenerator/ui/import_data.ui

+ Log messages colors
+ Order in plugin's submenu
+ Validation messages

Adjust 'Import Data'

---

projectgenerator/qgs_project_generator.py

@gacarrillor does this look good to you?

Mention interlis in menu entries

---

.docker/docker-compose.travis.yml

The containers postgres is not in same subnet that is specify for qgis see https://github.com/opengisch/projectgenerator/issues/104#issuecomment-330773178

Fix, no convergent network.

---

projectgenerator/gui/export.py
projectgenerator/gui/generate_project.py
projectgenerator/gui/import_data.py
projectgenerator/gui/multiple_models.py
projectgenerator/ui/export.ui
projectgenerator/ui/generate_project.ui
projectgenerator/ui/import_data.ui
projectgenerator/ui/multiple_models.ui

Support selection of multiple models in Generate/Import/Export dialogs

---

projectgenerator/libqgsprojectgen/generator/generator.py
projectgenerator/tests/test_domain_class_relations.py

This adds missing fixes from #112 which have been lost in transmission.

Various fixes

---

.travis.yml
projectgenerator/tests/test_yaml.py

fix unit tests, using qgis.testing instead of nose2.compact
https://github.com/nose-devs/nose2/blob/ac41ed2eea26f8bdd631f762b9ae46733d5a1a99/docs/changelog.rst#070

nose2.compact removed

---

projectgenerator/libili2db/ilicache.py

Recursive search of ilimodels in modeldir

Recursive search modeldir

---

projectgenerator/libili2db/ili2dbconfig.py
projectgenerator/libili2db/ili2dbutils.py
projectgenerator/libili2db/ilicache.py
projectgenerator/libili2db/ilidataimporter.py
projectgenerator/libili2db/iliexporter.py
projectgenerator/libili2db/iliimporter.py
projectgenerator/tests/test_libili2pg.py

Waiting answer from https://github.com/claeis/ili2db/issues/157

Fix recursive

---

projectgenerator/gui/export.py
projectgenerator/gui/generate_project.py
projectgenerator/gui/import_data.py
projectgenerator/libili2db/ili2dbconfig.py
projectgenerator/libili2db/ili2dbutils.py
projectgenerator/libili2db/ilicache.py
projectgenerator/libili2db/ilidataimporter.py
projectgenerator/libili2db/iliexporter.py
projectgenerator/libili2db/iliimporter.py
projectgenerator/tests/test_libili2pg.py
projectgenerator/ui/export.ui
projectgenerator/ui/generate_project.ui
projectgenerator/ui/import_data.ui

Adding progress bar to dialog generate, export and import

Progressbar

---

projectgenerator/libili2db/ili2dbconfig.py

Available at http://www.eisenhutinformatik.ch/interlis/ili2pg/

Update ili2pg to v3.11.2

---

projectgenerator/gui/import_data.py
projectgenerator/utils/qt_utils.py

References #131
References #15

Allow importing itf, xml, xls, xlsx

---

scripts/run-tests.sh

This are able to been executed since any directory:
**./scripts/run-tests.sh** or **./run-tests.sh** or **../scripts/run-tests.sh**

Simple script to execute tests locally

---

projectgenerator/libqgsprojectgen/dataobjects/project.py
projectgenerator/libqgsprojectgen/dataobjects/relations.py
projectgenerator/libqgsprojectgen/generator/generator.py

Fix domains for layers with multiple geometries

---

projectgenerator/utils/qgis_utils.py

+ Add your suggestions from #169 
+ Take into account rasters and tables
+ If this situation occurs in the layer tree:
+ Table/raster (or whatever lower than polygons in the desired order)
+ Polygon layer
And we want to insert a Line layer, don't insert it right before the polygon, but right before the table/raster. This works in a generic way, regardless of the types used in the example above.

Improve layer order by taking rasters and tables into account

---

projectgenerator/libqgsprojectgen/generator/generator.py
projectgenerator/tests/test_domain_class_relations.py

Configure domains for structures

---

.docker/Dockerfile
.docker/docker-compose.travis.yml
.travis.yml
requirements.txt

Using requirements.txt to update or install python packages.
This is related with https://github.com/opengisch/projectgenerator/pull/165

Using requirements.txt inside docker

---

projectgenerator/libqgsprojectgen/dataobjects/form.py
projectgenerator/libqgsprojectgen/dataobjects/layers.py
projectgenerator/tests/test_projectgen.py

In case it's container "General" otherwise the default value is still set to 1.

Create two columns for container

---

projectgenerator/libqgsprojectgen/dataobjects/relations.py

Fix #178
Tested with the Nucleo model

Do not freeze when a table has more than two geometries

---

projectgenerator/libili2db/ili2dbconfig.py
projectgenerator/libqgsprojectgen/generator/config.py
projectgenerator/tests/test_projectgen.py

Required to fix https://github.com/opengisch/projectgenerator/issues/159

Bump ili2gpkg to 3.11.3

---

projectgenerator/gui/export.py
projectgenerator/gui/generate_project.py
projectgenerator/gui/import_data.py
projectgenerator/gui/options.py
projectgenerator/libili2db/ili2dbconfig.py
projectgenerator/libili2db/ilidataimporter.py
projectgenerator/libili2db/iliexporter.py
projectgenerator/libili2db/iliimporter.py
projectgenerator/tests/test_domain_class_relations.py
projectgenerator/tests/test_export.py
projectgenerator/tests/test_import.py
projectgenerator/tests/test_projectgen.py
projectgenerator/tests/test_z_geom.py
projectgenerator/tests/utils.py
projectgenerator/ui/options.ui

Deduplication of code.
Introduces consistency between different commands (export/import/schemaimport)
* Password masking
* Usage of ili2db options
Makes maintenance easier and paramters available from the settings dialog
Fix #93

Refactor ili2db options

---

projectgenerator/gui/export.py
projectgenerator/gui/generate_project.py
projectgenerator/gui/import_data.py
projectgenerator/gui/options.py
projectgenerator/libili2db/ili2dbconfig.py
projectgenerator/libili2db/ilidataimporter.py
projectgenerator/libili2db/iliexporter.py
projectgenerator/libili2db/iliimporter.py
projectgenerator/tests/test_domain_class_relations.py
projectgenerator/tests/test_export.py
projectgenerator/tests/test_import.py
projectgenerator/tests/test_projectgen.py
projectgenerator/tests/test_z_geom.py
projectgenerator/tests/utils.py
projectgenerator/ui/options.ui

Add --coalesceArray and --coalesceMultiPoint

---

projectgenerator/gui/ili2db_options.py

Fixes what I broke with the last renaming of the file filter.

Fix toml file selector

---

projectgenerator/libqgsprojectgen/generator/domain_relations_generator.py
projectgenerator/tests/test_domain_class_relations.py
projectgenerator/tests/testdata/ilimodels/ZG_Naturschutz_und_Erholungsinfrastruktur_V1.ili

References #119 . Namely, see https://github.com/opengisch/projectgenerator/issues/119#issuecomment-381644131
Pending: Add test

Class-domain relations: Support abstract classes that extend from other abstract clases

---

projectgenerator/libili2db/ili2dbconfig.py
projectgenerator/libqgsprojectgen/generator/config.py

Add --importTid to schemaimport

---

projectgenerator/gui/export.py
projectgenerator/utils/qt_utils.py

Allow additional file types for export

---

projectgenerator/libqgsprojectgen/generator/generator.py

Disable estimated metadata by default

---

projectgenerator/libili2db/ili2dbconfig.py

Specify --import and --deleteData on data import

---

projectgenerator/gui/generate_project.py
projectgenerator/gui/ili2db_options.py
projectgenerator/gui/import_data.py
projectgenerator/libili2db/ili2dbconfig.py
projectgenerator/ui/ili2db_options.ui

Add option to create basket col

---

projectgenerator/gui/generate_project.py
projectgenerator/libqgsprojectgen/dataobjects/layers.py
projectgenerator/libqgsprojectgen/dataobjects/project.py
projectgenerator/libqgsprojectgen/dbconnector/db_connector.py
projectgenerator/libqgsprojectgen/dbconnector/gpkg_connector.py
projectgenerator/libqgsprojectgen/dbconnector/pg_connector.py
projectgenerator/libqgsprojectgen/generator/domain_relations_generator.py
projectgenerator/libqgsprojectgen/generator/generator.py
projectgenerator/metaproject.py
projectgenerator/tests/test_domain_class_relations.py
projectgenerator/tests/test_projectgen.py
projectgenerator/tests/test_projectgen_generic_databases.py
projectgenerator/tests/testdata/ilimodels/KbS_V1_3.ili

'BAG {} OF ENUM' support

---

projectgenerator/gui/export.py
projectgenerator/gui/generate_project.py
projectgenerator/gui/import_data.py
projectgenerator/gui/multiple_models.py
projectgenerator/libili2db/ilicache.py

Show source repository in model list

---

projectgenerator/gui/export.py
projectgenerator/gui/generate_project.py
projectgenerator/gui/import_data.py

instead of "startof" - match
fix: #214

Partly match of typed input in "Models"

---

projectgenerator/libqgsprojectgen/generator/generator.py
projectgenerator/tests/test_projectgen.py

Do not show [None] unit type

---

projectgenerator/tests/README.md

Otherwise, building the qgis image locally has troubles.

Add QGIS_TEST_VERSION to tests instructions

---

projectgenerator/utils/qt_utils.py

Pass filename via parameter

---

projectgenerator/gui/export.py

Fix #260 
Sorry @signedav I think you changed that on my request.

Catch connection errors when no connection is configured yet

---

projectgenerator/gui/export.py
projectgenerator/gui/generate_project.py
projectgenerator/gui/import_data.py
projectgenerator/libili2db/ili2dbutils.py
projectgenerator/utils/qt_utils.py

Function to differenciate info, warnings and errors using colors in Generate, Import and Export

---

projectgenerator/gui/generate_project.py
projectgenerator/gui/ili2db_options.py
projectgenerator/gui/import_data.py
projectgenerator/libili2db/ili2dbconfig.py
projectgenerator/ui/ili2db_options.ui

Add option for strokeArcs

---

QgisModelBaker/libqgsprojectgen/dataobjects/fields.py
QgisModelBaker/libqgsprojectgen/dbconnector/gpkg_connector.py
QgisModelBaker/libqgsprojectgen/generator/generator.py
QgisModelBaker/tests/test_gpkg_pk.py

Automatically generate primary keys for geopackage

---

QgisModelBaker/libili2db/iliexporter.py
QgisModelBaker/libili2db/iliimporter.py

Include double check as java can be found on different paths.

[fix] Include double check as java can be found on different paths

---

QgisModelBaker/libili2db/ili2dbconfig.py

Add --expandMultilingual

---

QgisModelBaker/libili2db/ili2dbutils.py
QgisModelBaker/utils/qt_utils.py

- Allow redirect in file download
- Fix the error message in file download

Fix the error message in file download

---

QgisModelBaker/images/QgisModelBaker-icon.svg
QgisModelBaker/images/QgisModelBaker-xtf-export-icon.svg
QgisModelBaker/images/QgisModelBaker-xtf-import-icon.svg

New cleaner icons

---

QgisModelBaker/qgismodelbaker.py

This pull requests aims to avoid displaying this message

Avoid critical message that always appears when installing Model Baker

---

QgisModelBaker/gui/panel/gpkg_config_panel.py
QgisModelBaker/gui/panel/pg_config_panel.py
QgisModelBaker/ui/gpkg_settings_panel.ui
QgisModelBaker/ui/pg_settings_panel.ui

This PR moves the GUI part from Python code to UI files for easing maintenance.

[gui] load panel settings from ui file

---

QgisModelBaker/gui/export.py
QgisModelBaker/gui/generate_project.py
QgisModelBaker/gui/import_data.py

- Clear the log message (txtStdout) when the selected target is changed.
- Disable target (type_combo_box) when it is executing.

Clear the log message (txtStdout) when the selected target is changed.

---

.travis.yml

this should result in faster jobs on Travis

use Docker without apt-get update

---

QgisModelBaker/gui/export.py
QgisModelBaker/gui/generate_project.py
QgisModelBaker/gui/import_data.py
QgisModelBaker/libqgsprojectgen/db_factory/pg_factory.py
QgisModelBaker/libqgsprojectgen/dbconnector/gpkg_connector.py
QgisModelBaker/tests/test_projectgen_generic_databases.py

On schema import (version check) since it's an issue for ili2db...

Do not create GPKG

---

QgisModelBaker/libqgsprojectgen/db_factory/db_simple_factory.py

If pyodbc is not installed (exception ModuleNotFoundError), SqlServer is not added to the list of available database

[mssql] Fix module not found error caused by pyodbc (#366)

---

QgisModelBaker/gui/generate_project.py

Fix exception when no model found in ili

---

QgisModelBaker/libili2db/ilicache.py
QgisModelBaker/tests/test_get_models.py
QgisModelBaker/tests/test_ilicache.py
QgisModelBaker/tests/testdata/ilimodels/DM01AVLV95LU2401.ili

Interlis 1 parsing was broken since merging #368

Fix Interlis 1 parsing

---

QgisModelBaker/libqgsprojectgen/db_factory/mssql_factory.py
QgisModelBaker/libqgsprojectgen/dbconnector/mssql_connector.py
QgisModelBaker/tests/test_domain_class_relations.py
QgisModelBaker/tests/test_export.py
QgisModelBaker/tests/test_projectgen.py

+ [x] Domain relations (ili2db4)
+ [x] Domain relations (ili2db3)
+ [x] test_meta_attr_hidden_toml_mssql
+ [x] test_export_mssql

Update ili2mssql tests for ili2db4

---

QgisModelBaker/libili2db/ili2dbconfig.py
QgisModelBaker/libqgsprojectgen/dbconnector/db_connector.py
QgisModelBaker/libqgsprojectgen/dbconnector/gpkg_connector.py
QgisModelBaker/libqgsprojectgen/dbconnector/mssql_connector.py
QgisModelBaker/libqgsprojectgen/dbconnector/pg_connector.py
QgisModelBaker/libqgsprojectgen/generator/generator.py
QgisModelBaker/tests/test_domain_class_relations.py
QgisModelBaker/tests/test_export.py
QgisModelBaker/tests/test_gpkg_pk.py
QgisModelBaker/tests/test_import.py
QgisModelBaker/tests/test_projectgen.py
QgisModelBaker/tests/test_z_geom.py

When the super class strategy is used and a t_type attribute is created to select the appropriate type, this is now offered as a combobox.
Fix #134 
CC @zigertiger

Create combo box for t_type attributes

---

.docker/docker-compose.travis.yml
.docker/run-docker-tests.sh
.travis.yml
QgisModelBaker/libqgsprojectgen/dbconnector/pg_connector.py
QgisModelBaker/tests/test_domain_class_relations.py
QgisModelBaker/tests/test_dump.py
QgisModelBaker/tests/test_export.py
QgisModelBaker/tests/test_gpkg_pk.py
QgisModelBaker/tests/test_import.py
QgisModelBaker/tests/test_projectgen.py
QgisModelBaker/tests/test_projectgen_generic_databases.py
QgisModelBaker/tests/test_z_geom.py
QgisModelBaker/tests/utils.py

Fix model baker with postgres 12

---

QgisModelBaker/libili2db/ilicache.py
QgisModelBaker/tests/test_ilicache.py
QgisModelBaker/tests/testdata/ilirepo/23/ilimodels.xml
QgisModelBaker/tests/testdata/ilirepo/24/ilimodels.xml

Support for IliRepository20

---

QgisModelBaker/gui/generate_project.py
QgisModelBaker/gui/ili2db_options.py
QgisModelBaker/gui/import_data.py
QgisModelBaker/libili2db/ili2dbconfig.py
QgisModelBaker/ui/ili2db_options.ui
QgisModelBaker/utils/qt_utils.py

Optionally, add preScript and postScript parameters to (schema) import

---

QgisModelBaker/libqgsprojectgen/db_factory/pg_factory.py

It might be something else than wrong credentials also

Add error message when database connection fails

---

QgisModelBaker/qgismodelbaker.py

Add version to about dialog

---

requirements.txt

https://github.com/psycopg/psycopg2/issues/854#issuecomment-611791946

use version > 2.8.3 for psycopg from python version 3.8

---

QgisModelBaker/gui/export.py

Fix wrong action name

---

QgisModelBaker/libqgsprojectgen/dbconnector/gpkg_connector.py
QgisModelBaker/tests/test_import.py
QgisModelBaker/tests/test_projectgen.py
QgisModelBaker/tests/testdata/ilimodels/CIAF_LADM/CIAF_LADM.ili

Support for scientific notation in GeoPackage numeric ranges

---

QgisModelBaker/libili2db/ili2dbconfig.py

Add 'baskets' and 'dataset' parameters for import/export operations

---

QgisModelBaker/libqgsprojectgen/generator/generator.py
QgisModelBaker/tests/test_projectgen.py

Such list is then added to the ModelBaker's default list.

Enable 3rd party plugins to set a list of layers to ignore

---

QgisModelBaker/libili2db/ili2dbutils.py

No longer force people to use legacy versions of java

ili2db also works with newer java version

---

QgisModelBaker/libili2db/ili2dbutils.py

Remove system import, we ship our own version

---

.github/workflows/continuous_integration.yml
QgisModelBaker/libqgsprojectgen/db_factory/gpkg_factory.py
QgisModelBaker/libqgsprojectgen/db_factory/mssql_factory.py
QgisModelBaker/libqgsprojectgen/db_factory/pg_factory.py
QgisModelBaker/tests/test_projectgen.py

push ili2pg to 4.4.6 with t_ili_id fix

---

QgisModelBaker/tests/test_domain_class_relations.py
QgisModelBaker/tests/test_dump.py
QgisModelBaker/tests/test_export.py
QgisModelBaker/tests/test_get_models.py
QgisModelBaker/tests/test_gpkg_pk.py
QgisModelBaker/tests/test_ili2dbutils.py
QgisModelBaker/tests/test_ilicache.py
QgisModelBaker/tests/test_import.py
QgisModelBaker/tests/test_projectgen.py
QgisModelBaker/tests/test_projectgen_generic_databases.py
QgisModelBaker/tests/test_update.py
QgisModelBaker/tests/test_yaml.py
QgisModelBaker/tests/test_z_geom.py

Instead of the unittest commands.

Use pytest `assert`

---

QgisModelBaker/gui/generate_project.py
QgisModelBaker/libqgsprojectgen/dataobjects/layers.py
QgisModelBaker/libqgsprojectgen/dataobjects/legend.py
QgisModelBaker/libqgsprojectgen/generator/generator.py
QgisModelBaker/tests/test_projectgen.py
QgisModelBaker/tests/testdata/ilirepo/24/layertree/opengis_layertree_KbS_LV95_V1_4.yaml
QgisModelBaker/tests/testdata/ilirepo/24/layertree/opengis_layertree_KbS_LV95_V1_4_GPKG.yaml

**Supported before**
```
group: true # if it's group or not (then layer) / default false
expanded: true # default true
```
**Supported now**
```
checked: true # if it's visible or not / default true
mutually-exclusive: true # on groups / default false
mutually-exclusive-child: -1 # on groups, index of child that is selected / default -1
```
**Supported before**
```
group: false # if it's group or not (then layer) / default false
```
**Supported now**
```
checked: true # if it's visible or not / default true
expanded: true # default true
featurecount: false # on layers / default false
```
**Not (yet) supported (and I don't know yet what they are for):**
```
legend_split_behavior="0"
legend_exp=""
patch_size="-1,-1"
overview
```
Not (yet) supported are style categories.
```
<categories> …
```

LegendItem options controlled by UsabILItyHub layertreestructure

---

QgisModelBaker/gui/generate_project.py
QgisModelBaker/tests/test_projectgen.py

because it has been not converted to a list

Fix remove on dict values object

---

QgisModelBaker/gui/generate_project.py
QgisModelBaker/utils/qt_utils.py

and reads last error from the validator in case of negative validation
fixes #442

Checks if file extension is ili (and not ILI)

---

QgisModelBaker/gui/panel/dataset_selector.py
QgisModelBaker/utils/db_utils.py

if one existing in the layer source

read username and password from the authconfig

---

QgisModelBaker/gui/export.py
QgisModelBaker/gui/generate_project.py
QgisModelBaker/gui/import_data.py
QgisModelBaker/gui/panel/pg_config_panel.py
QgisModelBaker/gui/workflow_wizard/database_selection_page.py
QgisModelBaker/gui/workflow_wizard/workflow_wizard.py

Validate if authcng is used in combination with superuser

---

QgisModelBaker/gui/panel/dataset_selector.py
QgisModelBaker/utils/db_utils.py

And do not try to connect when they are not valid. E.g. when the layer bases on a pg service, this check won't be valid.

Check validity of emitted db connection parameter from layer

---

QgisModelBaker/gui/workflow_wizard/workflow_wizard.py

...on export if there has been a basket handling. I think this wont fix issue #545 since the database part of the import configuration is updated when the export configuration changed. But this way won't be anyway less fault prone.
So this is not really a fix but more a beautification.

Check the export_data_configuration instead of the import_data_config

---

QgisModelBaker/gui/workflow_wizard/import_data_configuration_page.py
QgisModelBaker/gui/workflow_wizard/workflow_wizard.py
QgisModelBaker/qgismodelbaker.py

resolves #560
I reverted the stay-on-top flag on the windows. This leads to issue #564 but this is minor the #560

Fix strange behavior of dialog order

---

QgisModelBaker/gui/workflow_wizard/wizard_tools.py

The header section can be on multiple lines.

xtf parsing for models on multiple lines

---

QgisModelBaker/gui/workflow_wizard/workflow_wizard.py

Fix missing iface parameter

---

QgisModelBaker/gui/generate_project.py
QgisModelBaker/gui/import_data.py
QgisModelBaker/gui/workflow_wizard/import_schema_configuration_page.py
QgisModelBaker/gui/workflow_wizard/workflow_wizard.py
QgisModelBaker/qgismodelbaker.py

Having sub dialog on top.
fixes #564
Thanks for the input @m-kuhn

Fix weird dialog order in MS Windows

---

QgisModelBaker/libili2db/ilicache.py
QgisModelBaker/tests/testdata/ilirepo/24/ilidata.xml

I want to bring that into the official release.
So this is a backport.

[Backport] fix MultilingualText / LocalisedText Element for title in the ilicache

---

QgisModelBaker/libqgsprojectgen/generator/generator.py

to avoid crash when user made mistakes in his yaml tree.

check if item is a dict 

---

QgisModelBaker/qgismodelbaker.py

when it's dropped together with 'interlisish' files like xtf and ili - this resolves #590

accept xml in file drop

---

QgisModelBaker/libqgsprojectgen/dataobjects/layers.py
QgisModelBaker/tests/test_projectgen.py

Since Model Baker does not create always the BIDs correctly.
This might be reverted after we have a proper solution here #599

Set t_ili2db_basket table to writable

---

QgisModelBaker/libqgsprojectgen/dbconnector/gpkg_connector.py

Considering the T_KEY_OBJECT table simulating a global sequence number.
This is used because we edit the dataset and basket table.

Use fetch and increment of T_Id in geopackage 

---

QgisModelBaker/gui/dataset_manager.py

From
https://www.transifex.com/opengisch/QgisModelBaker/translate/#de/QgisModelBaker/330327885

Improve wording

---

.github/workflows/continuous_integration.yml

...and let em run...
Resolves #611

Bump QGIS test versions

---

QgisModelBaker/gui/workflow_wizard/export_data_configuration_page.py
QgisModelBaker/gui/workflow_wizard/workflow_wizard.py
QgisModelBaker/ui/workflow_wizard/export_data_configuration.ui

wizard page for export uses the same panel to filter the data as the validator

Reduce duplicate code by reusing filter panel

---

QgisModelBaker/gui/workflow_wizard/workflow_wizard.py

Since otherwise an update of a data from a model without stable BASKET IDs corrupts the previously imported data. 
This fixes #616 see there the analysis.

importBid should be set on any update command

---

QgisModelBaker/libqgsprojectgen/dataobjects/project.py
QgisModelBaker/libqgsprojectgen/generator/generator.py
QgisModelBaker/tests/test_projectgen.py

- Use correct name on the filter expression.
- Create default expression as well on gpkg mode

Fix basket handling with geopackage

---

.docker/run-docker-tests.sh
.github/workflows/continuous_integration.yml
QgisModelBaker/gui/generate_project.py
QgisModelBaker/gui/panel/pg_config_panel.py
QgisModelBaker/gui/workflow_wizard/project_creation_page.py
QgisModelBaker/libili2db/ili2dbconfig.py
QgisModelBaker/libqgsprojectgen/db_factory/db_simple_factory.py
QgisModelBaker/libqgsprojectgen/db_factory/pg_command_config_manager.py
QgisModelBaker/ui/pg_settings_panel.ui
QgisModelBaker/utils/db_utils.py

Pg service + sslmode support 

---

QgisModelBaker/libqgsprojectgen/dataobjects/layers.py
QgisModelBaker/tests/test_projectgen.py
QgisModelBaker/tests/testdata/ilimodels/Maps_V1.ili

Compare srid only if it is set

---

QgisModelBaker/gui/panel/dataset_selector.py
QgisModelBaker/gui/validate.py

To be able to check there if the layer is a gpkg or not. 
fixes #639 
and depends on https://github.com/opengisch/QgisModelBakerLibrary/pull/6/commits/759287f40dba1ebdcfc7c5bee3c4378d9f6176a2

pass source provider to the library function on validator and dataset selector

---

QgisModelBaker/utils/gui_utils.py

And escape parsing on XTF when it goes over 100 lines without any results

Parse ITF files for models to be listen in the model import dialog

---

QgisModelBaker/gui/validate.py
scripts/package_pip_packages.sh

Needs https://github.com/opengisch/QgisModelBakerLibrary/pull/17
And bump to 1.2.5 for the fixing #701

Fix check of datasource on none layers

---

QgisModelBaker/gui/validate.py

Menu entry to copy text from validator items

---

QgisModelBaker/gui/validate.py
QgisModelBaker/ui/validator.ui

Flash pan and zoom

---

QgisModelBaker/gui/validate.py
QgisModelBaker/ui/validator.ui

Depends on https://github.com/opengisch/QgisModelBakerLibrary/pull/20

Validator --skipGeometryCheck and --validConfig options

---

QgisModelBaker/ui/filter_data_panel.ui
QgisModelBaker/ui/validator.ui

Finetune validator GUI - remove margins

---

QgisModelBaker/gui/validate.py
QgisModelBaker/ui/validator.ui

do flash coordinates and features geometry

only pan when feature has geometry (and zoom to feature)

---

.github/workflows/continuous_integration.yml

And add it manually on every release...
https://github.com/opengisch/QgisModelBaker/issues/750

remove libs folder from release

---

QgisModelBaker/gui/workflow_wizard/project_creation_page.py
docs/background_info/usabilityhub/modelbaker_integration.md
docs/background_info/usabilityhub/technical_concept.md
docs/background_info/usabilityhub/user_guide.md
scripts/package_pip_packages.sh

See library part https://github.com/opengisch/QgisModelBakerLibrary/pull/41 and https://github.com/opengisch/QgisModelBakerLibrary/pull/42

UsabILIty Hub Mapthemes / Variables / Layout Import

---

.pre-commit-config.yaml
QgisModelBaker/gui/validate.py

and with this support custom model directories. Fixes #781

consider base config in the validation configuration 

---

QgisModelBaker/qgismodelbaker.py

Add the icon for the main menu entry

---

QgisModelBaker/gui/ili2db_options.py
QgisModelBaker/gui/workflow_wizard/workflow_wizard.py
QgisModelBaker/qgismodelbaker.py

Drag&Drop support for extra meta attribute files (toml/ini)

---

QgisModelBaker/qgismodelbaker.py

Just little less code and same implementation as other plugins like QFieldSync and PZP

Thinner implementation of plugin icon in menu

---

QgisModelBaker/gui/workflow_wizard/project_creation_page.py
QgisModelBaker/ui/workflow_wizard/project_creation.ui
scripts/package_pip_packages.sh

***Reworded to "Project optimization strategy concerning inheritances"***
Depends on - see there details as well https://github.com/opengisch/QgisModelBakerLibrary/pull/61

GUI for extended model optimization

---

.github/workflows/doc.yml

should bring better log messages
see https://github.com/transifex/cli/pull/157

upgrade Transifex client

---

docs/background_info/meta_attributes.md
docs/user_guide/import_workflow.md

See https://github.com/opengisch/QgisModelBakerLibrary/pull/78

Docu für Extra Meta Attr Prefix

---

QgisModelBaker/gui/panel/layer_tids_panel.py

display --- when no oid-domain defined

---

QgisModelBaker/gui/panel/basket_panel.py

like oid in 37d738827cd08725f486add07563ac3243b70e8b

display --- when no bid-domain defined

---

QgisModelBaker/utils/gui_utils.py

just not on dropping in qgis directly

accept xml files in wizard

---

QgisModelBaker/gui/workflow_wizard/project_creation_page.py
scripts/package_pip_packages.sh

introduced another bad behavior with the last fix...

unchain the optimize combo from topping results

---

QgisModelBaker/gui/dataset_manager.py
QgisModelBaker/gui/workflow_wizard/import_data_configuration_page.py
QgisModelBaker/utils/gui_utils.py

…, so that it's easier to identify them.
Requires: https://github.com/opengisch/QgisModelBakerLibrary/pull/100
Fix #600

[export] Include the basket's attachmentkey to the basket selection panel

---

QgisModelBaker/gui/dataset_manager.py
QgisModelBaker/gui/workflow_wizard/import_data_configuration_page.py

[gui] DatasetManagerDialog: Remove basket_integration in favour of wizard_embedded parameter

---

QgisModelBaker/gui/workflow_wizard/database_selection_page.py

set the list panel with the db_id instead of the mode. 

---

QgisModelBaker/gui/validate.py
QgisModelBaker/qgismodelbaker.py

i did not solve it with signals because we handle updates after closing dataset manager anyway in the main class.

refresh validator panel when added new dataset

---

QgisModelBaker/gui/workflow_wizard/project_creation_page.py

resolves #587
because not needed anymore since we have the superfancy new basket manager :shrug:

hide system layers in legend. 

---

.pre-commit-config.yaml
QgisModelBaker/gui/topping_wizard/ili2dbsettings_page.py

Depends on https://github.com/opengisch/QgisModelBakerLibrary/pull/121
https://github.com/user-attachments/assets/7a27b18a-3eb4-4b1e-9dd0-aee78143b194
Output file (extract):
Fix https://github.com/opengisch/QgisModelBaker/issues/796

[toppingwizard] Export all ili2db settings to metaconfig file

---

QgisModelBaker/gui/topping_wizard/ili2dbsettings_page.py
QgisModelBaker/gui/topping_wizard/layers_page.py
QgisModelBaker/gui/topping_wizard/models_page.py
QgisModelBaker/gui/topping_wizard/referencedata_page.py
QgisModelBaker/gui/topping_wizard/topping_wizard.py

busy bar on topping exporter

---

QgisModelBaker/gui/ili2db_options.py
QgisModelBaker/gui/panel/session_panel.py
QgisModelBaker/gui/workflow_wizard/default_baskets_page.py
QgisModelBaker/gui/workflow_wizard/execution_page.py
QgisModelBaker/gui/workflow_wizard/import_schema_configuration_page.py
QgisModelBaker/gui/workflow_wizard/project_creation_page.py
QgisModelBaker/gui/workflow_wizard/tid_configuration_page.py
QgisModelBaker/utils/gui_utils.py
scripts/package_pip_packages.sh

... and move loglevel to library
Requires https://github.com/opengisch/QgisModelBakerLibrary/pull/134

Pass log function to Project on Project Generate

---

scripts/package_pip_packages.sh

with this ili2db 5.3.1 and this resolves #664

bump mb to 1.10.2 

---

QgisModelBaker/gui/validate.py
QgisModelBaker/ui/validator.ui

No verbose:
Verbose:
Depends on https://github.com/opengisch/QgisModelBakerLibrary/pull/141
Fix #620

[gui] Add check box to activate verbose mode for the Validator

---

QgisModelBaker/gui/workflow_wizard/project_creation_page.py

(when using coalesceCatalogueRef)
Depends on https://github.com/opengisch/QgisModelBakerLibrary/pull/140
Fix #911

Suppress catalogue reference layers that don't have a BAG OF attribute
