opengisch/QgisModelBaker

- projectgenerator/libqgsprojectgen/dataobjects/legend.py
- projectgenerator/libqgsprojectgen/dataobjects/project.py
Moving layers takes a while, perhaps due to layer cloning. 
This PR improves our use case (+200 tables) in almost 40 seconds (from 2m23s to 1m42s).
> Optimize layer tree grouping (avoid moving layers)

- projectgenerator/gui/generate_project.py
- projectgenerator/libili2pg/iliimporter.py
- projectgenerator/libqgsprojectgen/dataobjects/project.py
- projectgenerator/qgs_project_generator.py
- projectgenerator/utils/qt_utils.py
-  On Windows, I've come across JAVA_HOME paths that come with quotes and need to be cleaned before we append 'java' to build the executable path.
-  If we load a model with no geometry tables, CRS would not be specified.
- Use psycopg2 to catch errors with PostgreSQL database connections. Empty host/database/user are handled via `QRegExpValidator` and communicated to the user, first through an orange color in the corresponding line edit, and, after clicking on `Create`, through a message and control focus.
- Subclass `QValidator` (`FileValidator`) to validate input Interlis files.
- Make sure we set an encoding for `decode()` functions in iliimporter.py Otherwise, we get `UnicodeDecodeError`'s.
> Handle some potential errors

- projectgenerator/libqgsprojectgen/dataobjects/layers.py
- projectgenerator/libqgsprojectgen/dataobjects/legend.py
- projectgenerator/libqgsprojectgen/dataobjects/project.py
- projectgenerator/libqgsprojectgen/generator/postgres/postgrescreator.py
1. Determine whether a table is a domain
- Only possible if metadata table (see https://github.com/claeis/ili2db/issues/63#issuecomment-290627830) exists
- If a schema is given, only query such schema 
2. Configure Relation Reference for domains (this may be reverted when embedded forms are disabled by default in QGIS)
3. Create layer-tree group for domains
4. Make domain tables read-only and collapse domains group
- Avoid adding domains group if no domains are found
References #18
References #8
> Domain configuration

- projectgenerator/libili2pg/ili2pg_config.py
- projectgenerator/libili2pg/iliimporter.py
- projectgenerator/libqgsprojectgen/generator/postgres/postgrescreator.py
- Add 2 new parameters to --schemaimport:
- --setupPgExt: see https://github.com/claeis/ili2db/issues/81
- --createMetaInfo: see https://github.com/claeis/ili2db/issues/63
- Add support for Units and MTEXT
- Update domain recognition: be aware of the tag 'ch.ehi.ili2db.tableKind' and its relevant values for domains (ENUM and CATALOGUE). See https://github.com/claeis/ili2db/commit/64a9b1411df35f103d8ab4b9895e1f0fcacdcbd5.
Fix #49
> Update to ili2pg v3.9.1

- projectgenerator/gui/generate_project.py
- projectgenerator/libili2pg/ilicache.py
- projectgenerator/libili2pg/iliimporter.py
- projectgenerator/qgs_project_generator.py
1. Adjust `placeholderText` for schema according to current mode (Interlis/PostGIS).
2. Parse local ili models with `utf-8` encoding. If that fails (`UnicodeDecodeError`), try with 'latin-1'. If that still fails, log it and continue silently. 
3. Since ili2pg creates the schema in lower case, deal with lower-case schemas in Project Generator. Otherwise, the plugin won't be able to load tables from the database when using schemas with capital letters.
4. Send ili file parameter to the end of the command.
> Random fixes

- projectgenerator/gui/generate_project.py
This part was missing from PR #63 :)
We are showing warning messages as INFOs (blue) and error messages as WARNINGs (orange). This is just to avoid scaring users with too strong colors. I hope it's ok for you.
> Show messages inside log panel in Generate dialog

- projectgenerator/gui/generate_project.py
- projectgenerator/libqgsprojectgen/generator/postgres/domain_relations.py
- projectgenerator/libqgsprojectgen/generator/postgres/postgrescreator.py
This PR enables Project Generator to automatically configure QGIS relations for Domain-Class pairs.
This approach should be temporary, as ili2pg will support Domain-Class FKs in v4.0 https://github.com/claeis/ili2db/issues/19
This PR doesn't set FKs in the database, but uses QGIS relations, and works for smart1Inheritance and smart2Inheritance.
References #8
> Automatic configuration of domains-class QGIS relations

- projectgenerator/libqgsprojectgen/generator/postgres/domain_relations.py
- Wrong assignation of domains if one name is contained in the other (ej: dom1 and dom10) (fixed REGEXP).
- Wrong treatment of extended attrs (fixed smart2 function to bring parent's attr name and pair it with child domain).
- Missing domain attributes inherited from parents and not extended in child class (fixed list of potential referencing classes by adding classes that extend other classes).
> Fix 3 issues with domain-class relations

- projectgenerator/libili2pg/ili2pg_config.py
- projectgenerator/libili2pg/iliexporter.py
`modeldir` param is not needed for Export, `ili2db` will get models from the database itself (table `t_ili2db_model`)
> Fix in Export

- projectgenerator/gui/export.py
- projectgenerator/gui/generate_project.py
- projectgenerator/gui/import_data.py
- projectgenerator/gui/options.py
- projectgenerator/ui/export.ui
- projectgenerator/ui/generate_project.ui
- projectgenerator/ui/import_data.ui
- projectgenerator/ui/options.ui
Add help button for the following dialogs boxes:
- Generate
- Import
- Export
- Settings 
This button redirects the user to the web page projectgenerator-docs, in the future we will be able to specify the index in each dialog according to the improvement of the documentation. 
Also change the title of generate.ui which was "Import Interlis" to "Generate Project"
> Add help button for generate - import - export - settings dialogs

- projectgenerator/gui/generate_project.py
- projectgenerator/libili2pg/ilicache.py
- projectgenerator/libili2pg/iliimporter.py
- projectgenerator/ui/generate_project.ui
- projectgenerator/utils/qt_utils.py
New proposal to deal with ili files and models when Generating Projects in Interlis mode.
+ ili file line edit goes before models line edit, because the former's value may impact the latter.
+ ili file line edit is valid if no value is given ("[Optional]" placeholder introduced) or an existing path is given.
+ If a valid and existing ili file is given:
+ Models line edit gets a `None` validator (since it becomes optional).
+ Completer changes to show only models from the given ili file.
+ --modelDir is not passed as argument to ili2db (parents of a given model from the ili file are searched for in modelDir and if not found there, ili2db throws errors, so it's safer not to pass it).
+ ili file is passed as argument to ili2db.
+ If there is no value for ili file:
+ Models line edit gets …
> Improve handling of ili files and models in Generate dialog

- .docker/run-docker-tests.sh
- projectgenerator/tests/README.md
A way to wait for postgres container to become available.
This is because 10 seconds is not sufficient to up postgres in all computers.
> Ensure a best and not arbitrary time.

- projectgenerator/gui/generate_project.py
- projectgenerator/libili2db/ilicache.py
- projectgenerator/libqgsprojectgen/dataobjects/legend.py
- projectgenerator/libqgsprojectgen/dbconnector/db_connector.py
- projectgenerator/libqgsprojectgen/dbconnector/gpkg_connector.py
- projectgenerator/libqgsprojectgen/dbconnector/pg_connector.py
- projectgenerator/libqgsprojectgen/generator/generator.py
- projectgenerator/qgs_project_generator.py
Other QGIS plugins (e.g., our [Asistente LADM_COL](https://github.com/AgenciaImplementacion/Asistente-LADM_COL)) may need to access Project Generator functionality, such as loading layers with forms, widgets and relations configured from a PostgreSQL schema. 
This PR exposes the `Generator` object (to build Project Generator data objects on demand) as well as a call to `Project.create_project()` to build the QGIS project. Additionally, this PR optimizes `DBConnector.get_relations_info()` so that it can use a list of layers and filter out information that is not required from the DB.
For reference, the Asistente LADM_COL uses such exposed methods [in this way](https://github.com/AgenciaImplementacion/Asistente-LADM_COL/blob/master/asistente_ladm_col/utils/project_generator_utils.py).
Fix …
> Make Project Generator useful from other plugins

- projectgenerator/libqgsprojectgen/generator/generator.py
When a table has multiple geometry columns it will be loaded several times.
In such a situation we also need to configure the relations accordingly.
Fix #116
> Relations for multi-geometry tables

- projectgenerator/libqgsprojectgen/dataobjects/legend.py
- projectgenerator/utils/qgis_utils.py
New layers will be added to a proper place in the layer tree, depending on its geometry type. 
Geometry layers are always loaded at the top of the layer tree, i.e., above groups (like `tables` and `domains`).
@m-kuhn I think we could add these methods in QGIS as well (taking rasters into account), as it may be a commonly desired behaviour.
> Order layers by geometry, even for subsequent calls to project.create()

- projectgenerator/libqgsprojectgen/generator/generator.py
> When units are defined, if alias is not found use column name

- projectgenerator/libqgsprojectgen/dataobjects/form.py
- projectgenerator/libqgsprojectgen/dataobjects/layers.py
In the QGIS VectorLayerProperties at AttributesForm-configuration as an item in the drop-list, there will be the relation.id as label and identificator. 
Fix of Redmines #18290
**I had not the yet possiblity to test**
In that form we work always with relation-id and not with the relation-name (altough it's saved under "FieldNameRole" - this is because the other fields use the name as unique identificator). That's why we exepct in the name-variable of `mLayer->editFormConfig().tabs()``the relation-id. This is why the projectgenerator would write after this commit there the relation-id and not the referencedlayer-name. It would have worked if it would have written the relation-name (but only because it's equal to relation-id).
*Same explanation in german:*
In den LayerProperties wird immer …
> Use relation.id instead of referencedlayer.name as identificator

- .docker/Dockerfile
This avoids `java.lang.NoClassDefFoundError: javax/xml/ws/Holder` error from Java 9, which is now the `default-jre` in Ubuntu repositories.
> Tests: Use openjdk-8-jre explicitly instead of 'default-jre' in Dockerfile

- projectgenerator/libqgsprojectgen/dataobjects/project.py
- projectgenerator/libqgsprojectgen/generator/generator.py
- projectgenerator/qgs_project_generator.py
We will need to turn transactions off in our LADM plugin, so having this as a parameter for `Project()` would be handy.
> Make transactions and evaluate_default_values optional parameters in Project dataobject

- projectgenerator/libqgsprojectgen/dbconnector/db_connector.py
- projectgenerator/libqgsprojectgen/dbconnector/gpkg_connector.py
- projectgenerator/libqgsprojectgen/dbconnector/pg_connector.py
- projectgenerator/libqgsprojectgen/generator/generator.py
We'd like to use the model from where each table comes in a custom "Load Layers" dialog of our Asistente LADM_COL plugin.
Since we can use several models in an ilid2b schema import operation, having the model in the table info from Project Generator will help us to organize available layers in a hierarchical tree.
> Add the model name for each table in tables_info (for both GPKG and PG)

- projectgenerator/libqgsprojectgen/dataobjects/form.py
- projectgenerator/libqgsprojectgen/dataobjects/layers.py
- projectgenerator/libqgsprojectgen/dataobjects/project.py
- projectgenerator/libqgsprojectgen/dbconnector/db_connector.py
- projectgenerator/libqgsprojectgen/dbconnector/gpkg_connector.py
- projectgenerator/libqgsprojectgen/dbconnector/pg_connector.py
- projectgenerator/libqgsprojectgen/generator/generator.py
- projectgenerator/tests/test_projectgen.py
In the attribute form configuration we set the FK of the layer referencing to the same layer (networktable) as the current layer is.
So this would look like this:
Instead of "Many to one" relation everywhere.
While the hinweisweiteredokumente_hinweis_fkey points to hinweisweiteredokumente_ursprung_fkey and hinweisweiteredokumente_ursprung_fkey to hinweisweiteredokumente_hinweis_fkey:
```
<widgets>
<widget name="hinweisweiteredokumente_hinweis_fkey">
<config type="Map">
<Option name="nm-rel" type="QString" value="hinweisweiteredokumente_ursprung_fkey"/>
</config>
</widget>
<widget name="hinweisweiteredokumente_ursprung_fkey">
<config type="Map">
<Option name="nm-rel" type="QString" value="hinweisweiteredokumente_hinweis_fkey"/>
</config>
</widget>
<widget …
```
> Set related layer on n-m cardinality

- projectgenerator/libili2db/ilicache.py
- projectgenerator/libqgsprojectgen/dbconnector/gpkg_connector.py
- projectgenerator/libqgsprojectgen/dbconnector/pg_connector.py
- projectgenerator/libqgsprojectgen/generator/generator.py
We've got plenty of
```
DeprecationWarning: invalid escape sequence \s
```
so let's change
```
'\s*CLASS match'
```
to
```
r'\s*CLASS match'
```
> Regex strings should be raw

- projectgenerator/libqgsprojectgen/generator/generator.py
Several tools from our LADM plugin simply don't work as expected because the number of features in the database doesn't match the number of features QGIS returns when `estimatedmetadata` is `True`.
This PR allows us to switch that parameter off, while avoiding to alter the current behaviour for the rest of Project Generator users.
I would say this is a critical issue for us.
**Example 1:**
+ A layer in the database contains several features but QGIS returns `0` when calling `layer.featureCount()`.
+ A tool initially checks whether the layer has features or not. If no features are found, the tool does not continue.
+ Since QGIS returns `0` for `layer.featureCount()`, the tool does nothing beyond the first check, generating confusion for the user, who may be even seeing spatial data on QGIS …
> Make PostgreSQL estimated metadata parameter optional in Generator class (by default True)

- .docker/docker-compose.travis.yml
Previously all tests would run on master and none on release-3_0.
> Run tests on specified QGIS version

- projectgenerator/utils/qt_utils.py
- Avoid error when selecting a GPKG file to save.
- Avoid appending '.gpkg' extension when not needed.
Problems introduced in https://github.com/opengisch/projectgenerator/commit/0c240b9567e4797c3638312947f31ec1d79a450b
> Fix GPKG save file selector

- projectgenerator/ui/options.ui
That always means an extra click for users, since we have no options in General.
> Avoid showing General tab as default in settings

- projectgenerator/gui/custom_model_dir.py
A minor modification is made to improve the usability in the add custom model dir functionality, so that in a single click to button "Add" we create a new list element and open the file explorer dialog to immediately set a path for it. 
This saves a couple of clicks for users.
> Improve usability while adding paths in custom model dir dialog

- projectgenerator/libqgsprojectgen/dataobjects/project.py
Let's take "Planerischer Gewässerschutz" as an example.
When creating a new "gwszone", a "status" needs to be defined. By default, no "status" is available, so one can draw a "gwszone" but will realize that he cannot save because "status" is mandatory but no options are available. So far one had to quit, go to the table, add a status, restart.
Now it's possible to add a new status directly from there.
Fix #197
> Allow adding new features in relation reference widgets

- projectgenerator/libili2db/ilicache.py
IMHO this is a solid solution, but I'm not sure if it could be nicer with something like `if any(model['name'] in s.data(int(Qt.DisplayRole)) for s in self):`...
#151
> Do not load duplicate model entries in GUI

- projectgenerator/gui/generate_project.py
- projectgenerator/libqgsprojectgen/dataobjects/layers.py
- projectgenerator/libqgsprojectgen/dbconnector/db_connector.py
- projectgenerator/libqgsprojectgen/dbconnector/gpkg_connector.py
- projectgenerator/libqgsprojectgen/dbconnector/pg_connector.py
- projectgenerator/libqgsprojectgen/generator/generator.py
- projectgenerator/tests/test_projectgen.py
We pick the first layer extent for setting the canvas extent. We could have used the union of all extents in the `t_ili2db_column_prop` table, but we didn't since the base geometry model is almost set in stone and all layers use the same definitions from such model. 
@m-kuhn What do you think about such approach? Do Swiss models use several base geometry models or extent definitions? 
2 tests added.
Fix #83
> Set map canvas extent to one obtained from the model (t_ili2db_column_prop table)

- projectgenerator/libqgsprojectgen/generator/domain_relations_generator.py
- projectgenerator/qgs_project_generator.py
- projectgenerator/tests/test_domain_class_relations.py
+ [x] Configure BAG OF ENUM for tables with more than one geometry column.
+ [x] Use the meta-attribute `mapping=ARRAY` from meta-attrs table.
+ [x] Add more checks for bags of enum configuration for the case where a list of layers is given. 
+ [x] Adjust the exposed `create_project` method to work with bags of enums.
> Improvements for BAG OF ENUM

- projectgenerator/gui/export.py
- projectgenerator/gui/generate_project.py
- projectgenerator/gui/import_data.py
- projectgenerator/gui/options.py
- projectgenerator/libili2db/ilicache.py
- projectgenerator/ui/export.ui
- projectgenerator/ui/generate_project.ui
- projectgenerator/ui/import_data.ui
Means it shows the filtered list if you change the original text.
If you click inside a lineedit with content it does not show the list until you change something.
If you click inside an empty lineedit it shows the unfiltered list.
If you delete the text of the lineedit it shows the unfiltered list.
Looks kind of like this:
It's about #212
> Flexible completion dropdown on model lineedit

- projectgenerator/gui/generate_project.py
- projectgenerator/gui/ili2db_options.py
- projectgenerator/gui/import_data.py
- projectgenerator/libili2db/ili2dbconfig.py
- projectgenerator/ui/ili2db_options.ui
This allows users to choose between create import tid column (`t_ili_tid`) on the data base (`True` by default):
> Make create import tid optional

- projectgenerator/gui/import_data.py
Also: Fix conditionals that weren't really working.
The crash happened on data Import, throwing this error: 
```
Stacktrace (piped through c++filt):
src/core/qgsmessagelog.cpp: 29: (logMessage) [1900ms] 2018-10-01T16:13:57 Qt[1] QSettings::value: Empty key passed
src/core/qgsmessagelog.cpp: 29: (logMessage) [120642ms] 2018-10-01T16:15:58 Python error[1] RecursionError: maximum recursion depth exceeded
Fatal Python error: Cannot recover from stack overflow.
Current thread 0x00007fa96cec9340 (most recent call first):
File "/home/germap/.local/share/QGIS/QGIS3/profiles/default/python/plugins/projectgenerator/libili2db/iliimporter.py", line 133 in stderr_ready
File "/home/germap/.local/share/QGIS/QGIS3/profiles/default/python/plugins/projectgenerator/gui/import_data.py", line 224 in on_stderr …
```
> Avoid QGIS crash by calling processEvents() only when required

- projectgenerator/gui/generate_project.py
- projectgenerator/libili2db/ili2dbconfig.py
- projectgenerator/libqgsprojectgen/dbconnector/pg_connector.py
- projectgenerator/libqgsprojectgen/generator/generator.py
Hi @m-kuhn, our new colleague @jhonalex06 attempted to use Project Generator using a database name with blank spaces and it threw a Python error. So he fixed that in this PR. 
He also noticed that using databases without PostGIS in the Generate dialog (Source: 'PostGIS') was throwing an error, and then he also fixed it in this PR.
In summary, this PR:
+ Adds support for database names with blank spaces.
+ Handles the PostGIS doesn't exist case in Generate->Source:PostGIS.
> Support database names with tblank spaces

- QgisModelBaker/libqgsprojectgen/dbconnector/pg_connector.py
Acknowledging that the underlying issue comes from ili2db ([the issue](https://github.com/claeis/ili2db/issues/255) is reported there already), this PR solves the problem in QGIS Model Baker.
This is the result using the same example reported in #286:
Fix #286
> Avoid duplicating fields (with units) in forms

- QgisModelBaker/gui/export.py
- QgisModelBaker/gui/generate_project.py
- QgisModelBaker/gui/import_data.py
- QgisModelBaker/libili2db/ili2dbconfig.py
- QgisModelBaker/libili2db/ili2dbutils.py
- QgisModelBaker/libili2db/iliexporter.py
- QgisModelBaker/libili2db/iliimporter.py
Because the QGIS startup script overwrites the env variables they need to be accessed in a different way.
This pull request:
* Deduplicates code and puts common code blocks into ili2dbutils.
* Extracts the original Windows `PATH` variable to look for the java executable
* Checks the java version and raises an error if people have installed an incompatible version
Fix #283
> Use global env to find java path on Windows

- QgisModelBaker/libili2db/ili2dbconfig.py
By default it will be false anyways, but this enables us to use the option from the Asistente LADM_COL plugin.
Highly required feature for interchanging (incomplete) data among different actors.
> Support disabling data validation on XTF import/export

- QgisModelBaker/libili2db/ili2dbutils.py
This solves the following issue:
by taking into account also Java version strings like: 
+ openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
For backwards compatibility, it has also been tested against strings like: 
+ java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
And continues working well.
> Adjust Java version parsing

- QgisModelBaker/libili2db/ilicache.py
There is an issue when the user has a .xtf loaded in the menu (Import Interlis Transfer File .xtf), but the file does not exist anymore.
Gif of the issue:
> Check that ili file exists before refreshing cache

- QgisModelBaker/gui/generate_project.py
- QgisModelBaker/gui/panel/db_config_panel.py
- QgisModelBaker/gui/panel/gpkg_config_panel.py
Also refresh validators.
Fix #325
> Refresh panels when switching modes in Generate Project dialog

- QgisModelBaker/gui/export.py
- QgisModelBaker/gui/import_data.py
When you import/export data and an error occurs, a new button is enabled that allows you to execute data import/export using `--disableValidation`.
We did our best trying to isolate errors that come from other sources, in fact, Model Baker already handles JAVA-related issues (no Java installed/given, no proper version) and connection issues very well.
References https://github.com/opengisch/QgisModelBaker/issues/318
> Add "import/export without validating" button

- QgisModelBaker/gui/export.py
- QgisModelBaker/gui/import_data.py
Refresh panels also in import data and export dialogs. Otherwise buttons to select GeoPackage files will not work.
> Follow up for fixing issue #325

- QgisModelBaker/libili2db/iliimporter.py
Fix importing error on Windows if the current locale is different than `UTF-8` and `locale.gelocale()` returns `None`.
Seems that `locale.getdefaultlocale()` (that let python try to determine the correct locale) works on these situations.
> Try with getdefaultlocale() if getlocale() fails

- QgisModelBaker/libili2db/iliexporter.py
Fix importing error on Windows if the current locale is different than UTF-8 and locale.gelocale() returns None.
Seems that locale.getdefaultlocale() (that let python try to determine the correct locale) works on these situations.
**This is exactly the same change as in #353 but on iliexporter instead of iliimporter**
> Try with getdefaultlocale() if getlocale() fails in iliexport

- QgisModelBaker/gui/export.py
- QgisModelBaker/gui/generate_project.py
- QgisModelBaker/gui/ili2db_options.py
- QgisModelBaker/gui/import_data.py
- QgisModelBaker/gui/panel/gpkg_config_panel.py
Uppercase extensions are valid now.
Otherwise it's hard to find the file, when its extension is written in uppercase letters.
The general validation is still case-sensitive if the local file system is case sensitive (e.g. unix afaik).
> Support uppercase file extensions

- QgisModelBaker/libili2db/ili2dbutils.py
- QgisModelBaker/libqgsprojectgen/dataobjects/project.py
- QgisModelBaker/libqgsprojectgen/db_factory/gpkg_factory.py
- QgisModelBaker/libqgsprojectgen/db_factory/pg_factory.py
- QgisModelBaker/libqgsprojectgen/dbconnector/db_connector.py
- QgisModelBaker/libqgsprojectgen/dbconnector/gpkg_connector.py
- QgisModelBaker/libqgsprojectgen/dbconnector/pg_connector.py
- QgisModelBaker/libqgsprojectgen/generator/generator.py
- QgisModelBaker/tests/test_domain_class_relations.py
- QgisModelBaker/tests/test_projectgen.py
- QgisModelBaker/tests/testdata/ilimodels/CardinalityBag.ili
Information for Bag-Of-Structures are read from the meta tables:
- t_ili2db_column_prop
- t_ili2db_meta_attrs
- t_ili2db_classname
The cardinality influences the Value Relation settings like this:
- Minimum Value: if 1 the constraint expression is set like `array_length("valuerelation_1")>0` means at least one item should be selected
- Maximum Value: no influece since it should be always * If not, then it's not an ARRAY and not created as a value relation
`Allow Null` and `Multi Selection` are always true, since the list is never NULL and if it should not be a multi selection the widget will be a Relation Reference.
Fix #359 
Fix #182
> Bag Of creating Value Relations with ili2db 4.4.0

- QgisModelBaker/gui/import_data.py
- QgisModelBaker/qgismodelbaker.py
After a data import it goes through all the layers, resets the data source and featureCount with the QGIS method `reloadData()` https://github.com/qgis/QGIS/pull/33259 and reloads the layer in the legend (to trigger the getter of the feature count).
**Before:**
After data import, canvas are not refreshed (still empty until first zoom or whatever) and the feature count has been - even after the features are loaded on the canvas - the same like before the data import...
> Refresh layers (including feature count) after data import

- QgisModelBaker/libili2db/ilicache.py
- QgisModelBaker/tests/test_ilicache.py
- QgisModelBaker/tests/testdata/ilimodels/RoadsInvalid.ili
- QgisModelBaker/tests/testdata/ilimodels/RoadsSimpleNoSpace.ili
Problem so far, the parser wasn't robust against no space between model name and language
```
NOT OK:
MODEL SZ_Lebensraum_Krebs_V2_Erfassung(de)
OK:
MODEL SZ_Lebensraum_Krebs_V2_Erfassung (de)
```
> Fix models without space

- QgisModelBaker/gui/export.py
The connection to clicked signal was done on every model refresh. Now it's only done once.
If a click event is executed twice, the checkbox was deselected and immediately selected again.
Fix #371
> Fix model selection at export

- QgisModelBaker/gui/export.py
When we try to export a XTF file the path does not get the extension. This PR fix this.
Solution:
> Fix get extension when try to export .xtf file

- QgisModelBaker/gui/import_data.py
Parses the command line output for a missing sequence error and gives a message that the model is missing.
Fix #381
> Warn when importing data for missing model

- QgisModelBaker/libili2db/ili2dbconfig.py
`importTid` and `exportTid` parameters make ili2db use `t_ili_tid` as id when importing/exporting XTFs.
> [api] Add import/export Tid as optional parameters

- QgisModelBaker/gui/generate_project.py
- QgisModelBaker/libili2db/ili2dbconfig.py
- QgisModelBaker/libqgsprojectgen/dataobjects/layers.py
- QgisModelBaker/libqgsprojectgen/dataobjects/project.py
- QgisModelBaker/tests/test_domain_class_relations.py
- QgisModelBaker/tests/test_export.py
- QgisModelBaker/tests/test_gpkg_pk.py
- QgisModelBaker/tests/test_import.py
- QgisModelBaker/tests/test_projectgen.py
- QgisModelBaker/tests/test_z_geom.py
and pass --defaultSrsAuth parameter to ili2db. 
Handles ili2db non-valid SRSs like USER:1234 (only valid for a single machine running QGIS) or srs codes that are not integers.
> Support for other SRS authorities

- QgisModelBaker/libqgsprojectgen/db_factory/gpkg_factory.py
- QgisModelBaker/libqgsprojectgen/db_factory/mssql_factory.py
- QgisModelBaker/libqgsprojectgen/db_factory/pg_factory.py
- QgisModelBaker/tests/test_import.py
- QgisModelBaker/tests/testdata/ilimodels/CHBase_Part4_ADMINISTRATIVEUNITS_20110830.ili
Notes: 
+ The URL to download ili2db tools has changed to a more standard URL that is going to be maintained.
+ t_ids in a test have been adjusted. I guess that sometimes new ili2db versions impose those adjustments, since it's not the first time it happens in some tests.
--------------
:warning:  8 tests fail due to stronger constraint data type checks in ili2c (see https://github.com/claeis/ili2c/issues/17). 
All 8 tests fail when using the model `ExceptionalLoadsRoute_LV95_V1`, throwing the following error: 
> ERROR    root:test_gpkg_pk.py:95 Error: /usr/src/QgisModelBaker/tests/testdata/ilimodels/CHBase_Part4_ADMINISTRATIVEUNITS_20110830.ili:142:incompatible datatypes
It's a Swiss model, so I wouldn't like to adjust the .ili file before bringing this topic here for some discussion.
> Update ili2db tool versions to v4.4.3

- QgisModelBaker/libqgsprojectgen/dataobjects/layers.py
If a layer has <6 visible attributes the form will be shown in single column mode.
With more in 2 column mode.
Fixes #196
> Show single column form for few attributes

- QgisModelBaker/gui/import_data.py
- QgisModelBaker/ui/import_data.ui
It's about this:
- having the checkbox unchecked on open of the dialog to avoid unintended overwriting and mostly you don't need it on second import.
- tooltip to get informed that catalogues are deleted as well
fixes #361
> Import data: Delete checkbox optimization

- QgisModelBaker/libqgsprojectgen/dataobjects/project.py
So far, related values (e.g., from a domain) are always required, and if users want to set a `NULL` value for the corresponding field, they have to write (manually) the word `NULL`, since, the X button in the field edit doesn't set the field's value to `NULL` (after all, `NULL` is not an allowed value according to the configuration).
> Allow NULLs in Relation Reference widgets when appropriate

- QgisModelBaker/qgismodelbaker.py
By using `show()` instead of `exec()`.
While the dialog is open the action toolbutton is checked.
(in the solution the newly opened dialogs are always on top - this screencast is obsolete)
Another possibility would be to have it like `tool_button.setDown()`, but then it's still enabled in the database menu.
This pretty sure fixes as well #314 because on Windows on focusing on QGIS the dialogs are raised.
> Keep QGIS enabled on generate, import and export dialog open

- QgisModelBaker/gui/export.py
- QgisModelBaker/gui/generate_project.py
- QgisModelBaker/gui/import_data.py
- QgisModelBaker/gui/panel/pg_config_panel.py
- QgisModelBaker/libili2db/ili2dbconfig.py
- QgisModelBaker/libqgsprojectgen/db_factory/db_command_config_manager.py
- QgisModelBaker/libqgsprojectgen/db_factory/gpkg_command_config_manager.py
- QgisModelBaker/libqgsprojectgen/db_factory/mssql_command_config_manager.py
- QgisModelBaker/libqgsprojectgen/db_factory/pg_command_config_manager.py
- QgisModelBaker/libqgsprojectgen/db_factory/pg_factory.py
- QgisModelBaker/libqgsprojectgen/dbconnector/pg_connector.py
- QgisModelBaker/libqgsprojectgen/generator/generator.py
- QgisModelBaker/ui/export.ui
- QgisModelBaker/ui/pg_settings_panel.ui
This pull requests adds compatibility for the auth management framework in QGIS. It will only store an authid in the QGIS project. The same authid will need to be configured on every QGIS profile that the project is opened.
Fixes #391
TODO:
> Add support for authentication configuration

- QgisModelBaker/gui/generate_project.py
- QgisModelBaker/libili2db/ili2dbconfig.py
Like the possibility to import and export without validation, we have now the possibility to import a **schema** without constraints.
If this is started, the ili2db command is run with this parameter:
- `--sqlEnableNull`
and without this parameters
- `--createNumChecks`
- `--createUnique`
- `--createFk`
`--createFkIdx` is still used, since it has nothing to do directly with constraints (it just indexes the column for the fks AFAIK)
resolves #427
Since on importing an xtf File the schema is created (if not existing) the import schema parameters are taken there as well. On "Import without validation" these constraint-parameters are not set.
> Import schema without constraints

- QgisModelBaker/gui/export.py
- QgisModelBaker/gui/generate_project.py
- QgisModelBaker/libili2db/ili2dbconfig.py
- QgisModelBaker/libili2db/iliexecutable.py
- QgisModelBaker/libili2db/iliexporter.py
- QgisModelBaker/libili2db/iliimporter.py
- QgisModelBaker/libili2db/iliupdater.py
- QgisModelBaker/tests/test_export.py
- QgisModelBaker/tests/test_update.py
- QgisModelBaker/tests/utils.py
- QgisModelBaker/utils/qt_utils.py
QgisModelBaker allows users to run these ili2db operations: Schema Import, Import, and Export.
This PR adds update operation support at the API level (class **Updater**). Because **Importer** and **Exporter** classes have a lot of common code and **Updater** would have the same code, this PR refactors that common code moving it to the new class **IliExecutable**. Also, it was created a specific configuration class: UpdateDataConfiguration.
> Add Iliupdater

- QgisModelBaker/libqgsprojectgen/dataobjects/fields.py
- QgisModelBaker/libqgsprojectgen/dataobjects/project.py
- QgisModelBaker/libqgsprojectgen/dataobjects/relations.py
- QgisModelBaker/libqgsprojectgen/dbconnector/db_connector.py
- QgisModelBaker/libqgsprojectgen/dbconnector/gpkg_connector.py
- QgisModelBaker/libqgsprojectgen/dbconnector/mssql_connector.py
- QgisModelBaker/libqgsprojectgen/dbconnector/pg_connector.py
- QgisModelBaker/libqgsprojectgen/generator/generator.py
- QgisModelBaker/tests/test_domain_class_relations.py
- QgisModelBaker/tests/testdata/ilimodels/ColorsParentChildDomain.ili
With ili2db 4.4.4 we have an update in domain inheritance.
If DomainB extends DomainA in the conceptual model, we end up with a single table in the database containing all values from DomainA plus all values from DomainB (there may be even repeated values if the value is let untouched from the parent domain). 
Example (single table where we have both parent and child domain values):
Therefore, for letting users pick a value from DomainB, we need to filter the values from the database.
The way of doing this is the following:
1. Read the `tag` "ch.ehi.ili2db.enumDomain" (new in ili2db 4.4.4) from table `t_ili2db_column_prop` and store it in a Field object.
2. When creating Relation objects, inspect the referenced table to know if we deal with domain-class relation. If so, go to referencing …
> Add support for filtering domain values for extended domains

- QgisModelBaker/libqgsprojectgen/dbconnector/db_connector.py
only omit tables that are referencing the detected ones
Fixes https://github.com/opengisch/QgisModelBaker/pull/421#discussion_r517069655
> Do not omit tables that are referencing staticly ignored tables

- QgisModelBaker/gui/import_data.py
- QgisModelBaker/gui/panel/gpkg_config_panel.py
- QgisModelBaker/libili2db/ili2dbconfig.py
Re-introduce parameter `--doSchemaImport` when the file (Geopackage) or the db schema (PG, MSSQL) does not exist.
Fixes #349
> Schema creation on XTF import

- QgisModelBaker/libili2db/iliexecutable.py
In the normal call of `QProcess` we use an array of arguments again instead of passing always a command.
If the command is edited, we pass the command. There a slight escaping is done by replacing `"` by `"""` and putting arguments with spaces into doublequotes.
This fixes #444
> Support arguments with spaces and quotes

- QgisModelBaker/gui/import_data.py
- QgisModelBaker/qgismodelbaker.py
- QgisModelBaker/tests/testdata/ilimodels/subparent_dir/not_hidden/CIAF_LADM.ili
- QgisModelBaker/tests/testdata/ilimodels/subparent_dir/not_hidden/Catastro_COL_ES.ili
Valid extensions for dropped files: 'xtf', 'itf', 'pdf', 'xml', 'xls', 'xlsx'
- when exactly one valid file is dropped and when import dialog is already open -> fill up import file field
- when exactly one valid file is dropped and when import dialog not yet open ->  open import dialog and fill up file field
- when one or more invalid files are dropped -> do normal QGIS behavior
- when one or more files are dropped containing at least one valid file -> show user feedback that Model Baker dialog cannot handle multiple files
> Open dropped XTF (or similar) file in Import Dialog

- QgisModelBaker/gui/drop_message.py
- QgisModelBaker/gui/options.py
- QgisModelBaker/libili2db/globals.py
- QgisModelBaker/qgismodelbaker.py
- QgisModelBaker/ui/drop_message.ui
- QgisModelBaker/ui/options.ui
**The behavior is:**
If not XTF / ITF -> QGIS default behavior
If XTF / ITF multiple files -> QGIS default behavior
If XTF / ITF single file -> Dialog asking what to do? -> selected behavior
IF XTF / ITF single file, and selected don't ask again in dialog -> last chosen behavior
> The difference to the last version with multiple files is, that the default behavior is taken instead printing a message: "Model Baker cannot handle multiple dropped files" - this because before the QGIS behavior is "removed" completely and now it's part of the solution, so it should be used still.
When dropping an XTF or an ITF file a dialog is opened:
On checking the checkbox, the behavior is used without popping up a dialog in future. To get the dialog again, the user can reset the "check" in the settings. …
> Drop XTF followup - ask the user if using Model Baker or QGIS default behavior

- QgisModelBaker/libili2db/ili2dbutils.py
- QgisModelBaker/tests/test_ili2dbutils.py
The old approach was locally searching for .ili files in the model directories
and recursively adding all of them. The setting actually supports a couple of
magic strings like `%XTF_DIR` and similar which got lost this way because
we couldn't glob them.
This approach always adds all directories from the setting and adds
additional subdirs only if they contain .ili files
Fixes #464
> Fix modeldir support of % values

- QgisModelBaker/libqgsprojectgen/dataobjects/legend.py
On having a project open and importing an additional model into the same schema /db file, the layers are reloaded and double. So the fix is, that it does not reload the already existing layers.
> No double loading of layers in layertree

- QgisModelBaker/libqgsprojectgen/generator/generator.py
- QgisModelBaker/tests/test_projectgen.py
- QgisModelBaker/tests/testdata/toml/multisurface.toml
These commits are cherrypicks from the branch of usabilityhub_toppings - I think it's better to consider it seperately.
**GeoPackage:**
fix layernames on tables that are created twice in geopackage  and contain the iliname with brackets (e.g. KbS_LV95_V1_4.Belastete_Standorte.Belasteter_Standort.Geo_Lage_Punkt(KbS_LV95_V1_4.Belastete_Standorte.Belasteter_Standort)) They are now named **Belasteter_Standort (Geo_Lage_Punkt)** This fixes #469
**Postgres:**
On creating layers from a Postgres dataset where a table has multiplegeometry columns, this table is loaded for each geometry column. To have a unique name, we check for duplicate tablenames and if we found one we check out the t_ili2db_attrname for the geometry column and add it's proper name to the table.
> Fix Layernames for tables with multiple geometry columns

- QgisModelBaker/libili2db/ili2dbconfig.py
- QgisModelBaker/libili2db/ilicache.py
- QgisModelBaker/tests/testdata/ilirepo/24/ilidata.xml
Because usabilityhub.opengis.ch is for the Website
> Use of models.opengis.ch instead of usabilityhub.opengis.ch

- .github/workflows/continuous_integration.yml
because otherwise no workflows are triggered on pre-release
> gh workflow - use published as type

- QgisModelBaker/gui/generate_project.py
- QgisModelBaker/gui/options.py
Loads and unloads the metaconfig model items (UsabILIty Hub Metaconfigurations) reliable.
Marks the box orange when the metaconfig string is not finding a metaconfiguration.
This fixes an unreliable behavior. The only unnice thingy left is #495 - but this is only visually.
> Fix unreliable drop down on metaconfig selection widget

- .github/workflows/continuous_integration.yml
`qgis-plugin-ci` already automatically uploads the artifacts for you.
> No need to explicitly upload artifacts

- QgisModelBaker/gui/generate_project.py
- QgisModelBaker/libili2db/ilicache.py
We do update the metaconfig line edit completer model on resetModel signal of the cache model.
When there are no metaconfigs found for it, then disable the widget.
On any change of the model we clean up the currently loaded metaconfig by clearing the metaconfig text. Except when the text is the same like the currently loaded metaconfig generated. So when the loading of the metaconfig updates the model text edit, it does not reset the metaconfig in the same step.
> Proper clean up of metaconfig when model changes

- QgisModelBaker/gui/generate_project.py
- QgisModelBaker/gui/import_data.py
Fixes #495
there is the punched signal requesting completion when getting focus or receiving mouse press. then there is the text change signal that requests completion because it's not done per default (i don't know why) and in the end there were two problems:
- does not make a completion on punching when the text is not empty
- does make a weird completion (with random values it seems) when finding one single entry
so it makes a complete() even on having a text and it makes no complete() when finding one single entry.
this might have been solved better, but at the moment I don't see a better sollution.
> Fix weird completer behavior

- QgisModelBaker/libqgsprojectgen/dataobjects/layers.py
and contiins relation editors and **not when it's a referencing layer (child)**
So this one is a referencing layer:
And this one is a referenced layer:
> Create tabs when the layer is the referenced layer (parent) 

- QgisModelBaker/gui/generate_project.py
- QgisModelBaker/gui/ili2db_options.py
- QgisModelBaker/libili2db/ili2dbconfig.py
- QgisModelBaker/libqgsprojectgen/dataobjects/form.py
- QgisModelBaker/libqgsprojectgen/dataobjects/layers.py
- QgisModelBaker/libqgsprojectgen/dataobjects/project.py
- QgisModelBaker/libqgsprojectgen/dbconnector/config.py
- QgisModelBaker/libqgsprojectgen/dbconnector/db_connector.py
- QgisModelBaker/libqgsprojectgen/dbconnector/gpkg_connector.py
- QgisModelBaker/libqgsprojectgen/dbconnector/mssql_connector.py
- QgisModelBaker/libqgsprojectgen/dbconnector/pg_connector.py
- QgisModelBaker/libqgsprojectgen/generator/config.py
- QgisModelBaker/libqgsprojectgen/generator/generator.py
- QgisModelBaker/tests/test_domain_class_relations.py
- QgisModelBaker/tests/test_export.py
- QgisModelBaker/tests/test_projectgen.py
`--createBasketCol` is active on default - you are still able to deactivate it.
When it's enabled, the following things are done:
- The layers have a `t_basket` column (ili2db) and the fields are integrated in the form.
- The layers `t_ili2db_basket` and `t_ili2db_dataset` are loaded in the project. They are needed to have the reference to them (to fill up `t_basket` in the single layers).
- For the layer `t_ili2db_basket` a display expression is created to provide the user a nice selection in the Relation Reference Widget of `t_basket`.
Questions:
- The "technical" tables `t_ili2db_basket` and `t_ili2db_dataset` are needed to be loaded. But where should they be placed? "Domain" would be a nice group since these are the tables the user usually is not interested in, but it's actually the …
> Basic Basket Dataset Support

- QgisModelBaker/ui/pg_settings_panel.ui
Add tabstops in the PostGIS settings panel to ease and/or speed up navigation with the keyboard
> Add tabstops in pg settings panel

- QgisModelBaker/gui/panel/gpkg_config_panel.py
- QgisModelBaker/utils/qt_utils.py
It still allows you to select an existing file.
The fix is needed to have the ability to choose a non-existing file, because you can create the GPKG with ili2db Parameter `--doschemaimport`.
Negative point is that because it's a default Qt Component (`QFileDialog`) on providing the ability to choose a non-exisiting file (by using `getSaveFileName`, it displays a warning like this when choosing an existing file:
So this could irritate the use, because we do not "replace" the file when importing into an existing GPKG-File.
So I'm not sure about this fix.
> Use save file browser for import data

- QgisModelBaker/libqgsprojectgen/dataobjects/form.py
- QgisModelBaker/libqgsprojectgen/dataobjects/layers.py
- QgisModelBaker/libqgsprojectgen/generator/generator.py
- QgisModelBaker/tests/test_projectgen.py
Create multiple relation editor widgets for same relation close #505
Notes:
- For many to many relations the cardinality is set to the the linked parent table
- If the link table has additional attributes that are not foreign keys (Associations with attributes), an additional relation editor widget pointing to the link table is added
> Create multiple relation editor widgets for same relation

- QgisModelBaker/libqgsprojectgen/dbconnector/gpkg_connector.py
- QgisModelBaker/libqgsprojectgen/dbconnector/mssql_connector.py
- QgisModelBaker/libqgsprojectgen/dbconnector/pg_connector.py
- QgisModelBaker/tests/testdata/ilimodels/OeVBasketTest_V1.ili
The parsing was not stable when there are STRUCTURES in the INTERLIS Model that are not in a Topic.
This fixes the basic problem of #533
Not yet solved is being able to choose the correct basket for the STRUCTURE that could be related from classes from several topics.
> Fix Topic parsing

- QgisModelBaker/utils/db_utils.py
This fixes this part https://github.com/opengisch/QgisModelBaker/issues/528#issuecomment-914019808 but the rest of #528 persists (reported here #472).
> if authConfigId provided from datasource (PG) use it for getting the connection

- QgisModelBaker/gui/panel/dataset_selector.py
- QgisModelBaker/libqgsprojectgen/dataobjects/project.py
- QgisModelBaker/libqgsprojectgen/generator/generator.py
- QgisModelBaker/tests/test_projectgen.py
Like structs that are used in multiple topics. E.g. the `parzellenidentifikation` in `KbS_Basis_V1_3` or this simple test model:
```
MODEL NoTopicStruct (en) 
AT "https://signedav.github.io/usabilitydave/models"
VERSION "2020-06-22" =
STRUCTURE NoTopicStructure =
Name: TEXT;
Street: TEXT;
END NoTopicStructure;
TOPIC TopicA =
CLASS PersonInTopicA =
Address: NoTopicStructure;
Remark: TEXT*254;
END PersonInTopicA;
END TopicA; !! of TOPIC
TOPIC TopicB =
CLASS PersonInTopicB =
Address: NoTopicStructure;
Remark: TEXT*254;
END PersonInTopicB;
END TopicB; !! of TOPIC
END NoTopicStruct. !! of MODEL
```
All Baskets of the Dataset are listed in the Dataset Selector:
And in the display expression of the `t_ili2db_basket` table the topic is shown (instead of mostly abstract id):
This finalizes the …
> Correct basket handling of tables having no topic

- QgisModelBaker/gui/panel/dataset_selector.py
- QgisModelBaker/utils/db_utils.py
When connecting to a layer based on an XTF file (what returns as datasourcename OGR), the get db connector failed. This is caught by the try.
> Fix error when trying to connect to an XTF datasource

- QgisModelBaker/libili2db/ilicache.py
- QgisModelBaker/tests/testdata/ilirepo/24/ilidata.xml
In http://models.interlis.ch/core/DatasetIdx16.ili the attribute title is of type `MultilingualText` and not `MultilingualMText`.
What would happen when the fixed ModelBaker parses unfixed ilidata.xml or vice versa? - It would take the id as description. So no problem for me to merge that even when people have invalid ilidata.xml.
> Fix MultilingualText / LocalisedText Element for title in the ilicache

- QgisModelBaker/qgismodelbaker.py
when it's dropped together with 'interlisish' files like xtf and ili - this resolves #590
> [Backport] accept xml in file drop

- QgisModelBaker/libili2db/ilicache.py
- QgisModelBaker/tests/test_ilicache.py
- QgisModelBaker/tests/testdata/ilirepo/invalid/ilidata.xml
- QgisModelBaker/tests/testdata/ilirepo/invalid/ilimodels.xml
Parsing the `ilimodel.xml` / `ilidata.xml` we sometimes need to check the found element if it's empty before we access it's text. Mostly we trusted that the data has been correctly setup and the elements are there, we are looking for, but in case this is not the case Model Baker crashed. With this helper function `get_element_text` we even can remove some checks for element and make the code slimmer.
> Avoid crash when text of element cannot be found

- QgisModelBaker/gui/panel/session_panel.py
- QgisModelBaker/libili2db/ili2dbconfig.py
- QgisModelBaker/libqgsprojectgen/dbconnector/db_connector.py
- QgisModelBaker/libqgsprojectgen/dbconnector/gpkg_connector.py
- QgisModelBaker/libqgsprojectgen/dbconnector/mssql_connector.py
- QgisModelBaker/libqgsprojectgen/dbconnector/pg_connector.py
- QgisModelBaker/tests/test_import.py
In the wizard, we get the `TidHandling` from settings table to decide if `--importTid` / `--exportTid` needs to be passed on data import/export. `TidHandling` is in the `t_ili2db_settings` table when `--createTidCol` is passed on schema import. This means always when it's created by Model Baker. 
This fixes #601 and keeps the behavior of the single dialogues how it is (a little confusing but as we are used to).
> Fix the importTid/exportTid handling in Wizard

- QgisModelBaker/gui/ili2db_options.py
- QgisModelBaker/gui/import_data.py
- QgisModelBaker/ui/ili2db_options.ui
At:
- single dialog to generate project (schema import) because it does not anything
- wizard (where we have it only on schema import) because it does not anything
It's not hidden in single import data to provide the backwards compatibility.
But this setting shouldn't be made anyway. On import we can decide according to the column if we should make `importTid` and on schema import it does not make anything.
It's connected to this implementation #603
> Hide create Import Tid in the GUI

- QgisModelBaker/gui/dataset_manager.py
For IDs in the Dataset Manager.
This might be not conform with the definition in the model (see #599), so we tell the user about it.
> Info that on basket creation UUIDs are used

- docs/background_info/basket_handling.md
- docs/index.md
- docs/theme_overrides/404.html
- docs/theme_overrides/home.html
- docs/theme_overrides/main.html
- mkdocs.yml
- Basket Handling section about BASKET OID
- landing page with Model Baker abstract - it's less confusing anymore
- People following links to the old docu, got a weird 404 page. This is now overridden by a page explaining the issue. This fixes  #636
> Part about BASKET OID and landing page

- QgisModelBaker/libili2db/ilicache.py
Means when having `https://models.repo.ch/modeldirectory` it's joined to  `https://models.repo.ch/modeldirectory/ilimodels.xml` instead to follow the logic that a directory needs to end with a `/` what would lead to `https://models.repo.ch/ilimodels.xml` 
fixes #646
> Join the file to the the url as a path

- scripts/package_pip_packages.sh
because qgis-plugin-ci needs it for release
> set write rights to lib folder 

- QgisModelBaker/gui/panel/dataset_selector.py
- QgisModelBaker/gui/validate.py
- QgisModelBaker/gui/workflow_wizard/project_creation_page.py
- QgisModelBaker/utils/gui_utils.py
- scripts/package_pip_packages.sh
We do export the t_ili_tid (OID) with the parameter `--exportTid`. This is done automatically when an OID is defined in the model. If not defined, it needs this parameter to export stable ids.
So those t_ili_tid are checked on validation on export. Because they are not mandatory in the db when not defined in the model. But to provide stable ids they need to be checked.
So the validator should do the same.
This fixes  #699
It requires version 1.2.0 of the modelbaker libray. There it sets as well default values (UUID) for the t_ili_tid of the generated projects.
> Set `--exportTid` in validator

- QgisModelBaker/utils/gui_utils.py
Check if a same model name with lv95 instead lv03 is already loaded to decide if model should be checked. 
This fixes #598
> Disable LV03 models when LV95 have found

- QgisModelBaker/gui/panel/session_panel.py
Set button to "Run without validation" when the import/export fails. Not when it fails because of a `JavaNotFoundError`. Only when the importer/exporter returns false.
On schema import this button is not changed. Because there it's not succeeding with this setting. With this settings it just creates a schema allowing NULL values etc.
This fixes #672
> Change Button to "Run without validation" on failing import/export

- QgisModelBaker/gui/dataset_manager.py
- QgisModelBaker/gui/panel/log_panel.py
- QgisModelBaker/gui/topping_wizard/layers_page.py
- QgisModelBaker/gui/topping_wizard/topping_wizard.py
- QgisModelBaker/gui/validate.py
- QgisModelBaker/gui/workflow_wizard/workflow_wizard.py
- QgisModelBaker/ui/topping_wizard/layers.ui
- QgisModelBaker/ui/workflow_wizard/database_selection.ui
- check layer before getting dataSource. fixes #726
- Better column naming / tooltips and description on layer page of
- Logic on layer page that when definition is selected, the style and source get deselected (and the other way around) See movie below.
- Locic on layer page that when a parent has the definition selected the children get deselected (and the other way around) See movie below.
- make the wizard dialog expandable and shrinkable what fixes #725
[Screencast from 14.09.2022 13:39:08.webm](https://user-images.githubusercontent.com/28384354/190144816-f5537cf7-e4b9-468f-97d1-71633d8fb114.webm)
Not scope here:
- Layer Page: Settings Button of Categories should be closer to checkbox
- Layer Page: Style checkbox should be tristated when not having all categories to be exported
> Fixes and Improvements UsabILIty Hub Topping Exporter

- QgisModelBaker/utils/gui_utils.py
When no db_connector found (because any reason) the models should still be refreshed listing no models / datasets etc. This fixes  #731
> Handle invalid db_connectors

- QgisModelBaker/gui/validate.py
- QgisModelBaker/ui/validator.ui
First there is an error count:
On zoom to coordinates, the get highlighted.
And second I changed the behavior that on having coordinates zoom to feature and flash features are now zooming and flashing the coordinates. Only pan, does pan the features.
> Validate Pan Zoom improvements and error count

- QgisModelBaker/gui/topping_wizard/additives_page.py
- QgisModelBaker/gui/topping_wizard/layers_page.py
- QgisModelBaker/gui/topping_wizard/topping_wizard.py
- QgisModelBaker/ui/topping_wizard/additives.ui
- QgisModelBaker/utils/gui_utils.py
And it exports all the styles (with category settings per layer).
This is a very basic page to export those settings. It can be improved:
*But the request was to export them without any settings. But it was possible to make this with a small effort.*
**Concerning Styles:**
It would really, really make sense to be able to control what styles need to be exported *how* (what categories). For that I opened an issue #766
> Topping Exporter: Additive Project Settings (MapThemes, Variables and Layouts)

- QgisModelBaker/gui/validate.py
- QgisModelBaker/ui/validator.ui
- docs/user_guide/validation.md
With this change we pan to the coordinates. When no coordinate available, then we pan to the feature geometry (according to the provided OID). Same for zoom. On zooming to a feature geometry, we take it's extent.
1. Coord and OID available
2. Only OID available
3. Only Coord available
**Status before:**
1. Pan to features centroid
2. Pan to features centroid
3. Nothing
**Implemented here*
1. Pan to coordinates
2. Pan to features
3. Pan to coordinates
Because we do receive error messages concerning text value but providing coordinates as well as geometry errors  providing OID, sometimes it can be confusing why it pans to the coordinates. See the discussion here #747
**Status before:**
1. Zoom to features
2. Zoom to features
3. Zoom to coordinates
**Implemented here*
1. Zoom to coordinates …
> Validator: Pan and zoom to coordinate (whenever possible)

- QgisModelBaker/gui/panel/session_panel.py
- QgisModelBaker/gui/validate.py
- QgisModelBaker/gui/workflow_wizard/execution_page.py
- QgisModelBaker/gui/workflow_wizard/project_creation_page.py
- QgisModelBaker/gui/workflow_wizard/workflow_wizard.py
- QgisModelBaker/utils/gui_utils.py
This PR resolves three topics:
~- [x] Canceling all session when closing the wizard dialog. Resolves #714~
Requires https://github.com/opengisch/QgisModelBakerLibrary/pull/39
> Session panel improvements (cancel java, re-run process)

- QgisModelBaker/gui/generate_project.py
- QgisModelBaker/gui/ili2db_options.py
- QgisModelBaker/gui/import_data.py
- QgisModelBaker/gui/topping_wizard/ili2dbsettings_page.py
- QgisModelBaker/gui/workflow_wizard/import_schema_configuration_page.py
- QgisModelBaker/ui/ili2db_options.ui
- QgisModelBaker/ui/topping_wizard/ili2dbsettings.ui
- docs/background_info/meta_attributes.md
- docs/background_info/usabilityhub/user_guide.md
- docs/user_guide/import_workflow.md
And name it everywhere Extra Meta Attribute File instead of Extra Model Information File or similar.
But main change is that it should allow `ini` in the file selector of the usabilityhub exporter here https://github.com/opengisch/QgisModelBaker/compare/master...getridoftoml#diff-07f6e644349cc8752fc57b115d4e2d8dc52e913dcb53b53a742373e4d6ba5b14L137
> Allow `ini` for the Extra Meta Attribute File

- .docker/Dockerfile
- QgisModelBaker/gui/workflow_wizard/import_data_configuration_page.py
- QgisModelBaker/gui/workflow_wizard/workflow_wizard.py
- docs/background_info/usabilityhub/modelbaker_integration.md
- scripts/package_pip_packages.sh
Because it leads to issues. It's not removed from the backend, since it's still a valid parameter to use there.
See issue for possible enhancement https://github.com/opengisch/QgisModelBaker/issues/786
> Reset Metaconfig on Data Import / Update

- QgisModelBaker/gui/panel/export_models_panel.py
- QgisModelBaker/gui/panel/session_panel.py
- QgisModelBaker/gui/validate.py
- QgisModelBaker/gui/workflow_wizard/execution_page.py
- QgisModelBaker/gui/workflow_wizard/export_data_configuration_page.py
- QgisModelBaker/gui/workflow_wizard/workflow_wizard.py
- QgisModelBaker/ui/export_models_panel.ui
- QgisModelBaker/ui/validator.ui
- QgisModelBaker/ui/workflow_wizard/export_data_configuration.ui
- QgisModelBaker/utils/gui_utils.py
- scripts/package_pip_packages.sh
Resolves #665
If your data is in the format of the cantonal model, but you want to export/validate it in the format of the national model, you have to pass `--exportModels`, otherwise (or if the data cannot be exported/validated in the selected model because it's not an extension of it) the data is exported/validated in the model it is stored.
Usually, this is one single model. However, it is also possible to pass multiple models, which makes sense if there are multiple base models in the schema you want to export/validate.
Looks like this:
as well there is a tooltip listing all the relevant parent models (the ones that are listed as well, means are exportable):
and there is the info on the session:
When **validating** it without without `--exportModels` all the constraints must be …
> Graphical user interface to pass `--exportModels` to ili2db on export or validation.

- QgisModelBaker/gui/panel/export_models_panel.py
This here https://github.com/opengisch/QgisModelBaker/pull/800/commits/21604c6159ccf1d572d233b7a0cf74562c09fb0e introduced the error that the model is not loaded according to the layer in the validator.
It needs to set the model new and it needs to disconnect and reconnect the sloths. Now it does re-set the model on setup dialog to be stable on validation gui and on export data page.
> Fix broken export models gui on validator.

- QgisModelBaker/gui/topping_wizard/referencedata_page.py
- QgisModelBaker/gui/workflow_wizard/import_data_configuration_page.py
- QgisModelBaker/gui/workflow_wizard/import_schema_configuration_page.py
- QgisModelBaker/gui/workflow_wizard/import_source_selection_page.py
- QgisModelBaker/gui/workflow_wizard/workflow_wizard.py
Before it has been sorted like it has been added to the model. Means mostly it had kind of unstable sorting according the repository. This repository sorting is gone, but I think it's fine, mostly you look after a model name you know.
[Screencast from 05.05.2023 08:36:48.webm](https://user-images.githubusercontent.com/28384354/236391540-b8a0cff4-916f-46fe-8f7d-baa2e9587f98.webm)
First model on a punch is now AGNES, what is kind of nice, since it's a female name and the title of quite a nice novel by Peter Stamm.
This requires https://github.com/opengisch/QgisModelBakerLibrary/pull/58 and resolves https://github.com/opengisch/QgisModelBaker/issues/471
> Sort models / toppings in autocompleter box 

- QgisModelBaker/gui/workflow_wizard/import_schema_configuration_page.py
- QgisModelBaker/ui/workflow_wizard/import_schema_configuration.ui
- scripts/package_pip_packages.sh
Together with https://github.com/opengisch/QgisModelBakerLibrary/pull/59 it resolves #756
1. The UsabILIty Hub Exporter generates the `title` according to the project name and additionally the `shortDescription` in the way it created the `title` before.
2. The `shortDescription` is now provided as Tooltip
3. The `shortDescription` is added to the GUI when the metaconfig is selected.
> print short description when a metaconfig has been selected

- QgisModelBaker/gui/validate.py
I think the current layer should be set only if the dock widget is visible.
@signedav this change would mitigate the symptoms of an error that I saw. Maybe do you understand the root cause?
```
An error has occurred while executing Python code: 
sqlite3.OperationalError: near "take": syntax error 
Traceback (most recent call last):
File "C:\Users/lunic/AppData/Roaming/QGIS/QGIS3\profiles\lucie/python/plugins\QgisModelBaker\gui\validate.py", line 229, in set_current_layer
self.current_configuration.with_exporttid = self._get_tid_handling()
File "C:\Users/lunic/AppData/Roaming/QGIS/QGIS3\profiles\lucie/python/plugins\QgisModelBaker\gui\validate.py", line 283, in _get_tid_handling
db_connector = db_utils.get_db_connector(self.current_configuration)
File …
```
> Set current layer only if validate dock is visible

- QgisModelBaker/gui/export.py
- QgisModelBaker/gui/generate_project.py
- QgisModelBaker/gui/import_data.py
- QgisModelBaker/gui/panel/session_panel.py
- QgisModelBaker/gui/validate.py
> Add a visible error dialog in case Java is not installed. Fix #785

- QgisModelBaker/gui/workflow_wizard/import_source_selection_page.py
- QgisModelBaker/gui/workflow_wizard/workflow_wizard.py
Fix #776
Depends on https://github.com/opengisch/QgisModelBakerLibrary/pull/60
> Clear ilicache button

- QgisModelBaker/gui/validate.py
Still there are schemas based on 3.x.x we want to export and as well *validate*.
Requires https://github.com/opengisch/QgisModelBakerLibrary/pull/65
> Validation of Schemas based on ili2db 3.x.x

- QgisModelBaker/gui/workflow_wizard/import_source_selection_page.py
- QgisModelBaker/gui/workflow_wizard/workflow_wizard.py
- QgisModelBaker/qgismodelbaker.py
- QgisModelBaker/utils/gui_utils.py
> Support drop of INI Files as well in Source Selector

- QgisModelBaker/gui/validate.py
It didn't converted the path to absolute, because the file was not recognized
> Fix absolute path conversion

- .github/workflows/continuous_integration.yml
- QgisModelBaker/gui/panel/db_config_panel.py
- QgisModelBaker/gui/panel/gpkg_config_panel.py
- QgisModelBaker/gui/panel/mssql_config_panel.py
- QgisModelBaker/gui/panel/pg_config_panel.py
- QgisModelBaker/ui/pg_settings_panel.ui
Postgres available schema list is read directly from the database and presented in a combo box. Still it is possible to manually entry a new schema name.
Fix #456 
Depends on https://github.com/opengisch/QgisModelBakerLibrary/pull/70
> Schemas combobox

- QgisModelBaker/gui/workflow_wizard/import_data_configuration_page.py
- QgisModelBaker/gui/workflow_wizard/workflow_wizard.py
- Page order
- Delegate in Import Data Page
> Wizard workflow fix

- QgisModelBaker/qgismodelbaker.py
- QgisModelBaker/utils/gui_utils.py
They are already handled by FileDropListView.ValidExtenstions
Fix #837
> Don't handle xml files 2 times

- QgisModelBaker/gui/topping_wizard/models_page.py
- QgisModelBaker/gui/topping_wizard/referencedata_page.py
- QgisModelBaker/gui/topping_wizard/topping_wizard.py
- QgisModelBaker/gui/workflow_wizard/import_data_configuration_page.py
- QgisModelBaker/gui/workflow_wizard/import_schema_configuration_page.py
- QgisModelBaker/gui/workflow_wizard/import_source_selection_page.py
- QgisModelBaker/ui/topping_wizard/models.ui
- docs/background_info/usabilityhub/technical_concept.md
In the `ilidata` it's the `category` with the key `http://codes.modelbaker.ch/preferredDataSource` describing what db the file is made for. If there is no such category it's always displayed.
Filters UsabILIty Hub Metaconfig Files according to the current database.
It detects what db sources are used and suggests you to optimize. But you can choose none - means the topping will be displayed on every db source...
Resolves #759
Depends on https://github.com/opengisch/QgisModelBakerLibrary/pull/79
> UsabILItyHub: Filter Toppings according to the Database Source

- QgisModelBaker/gui/workflow_wizard/project_creation_page.py
Requires https://github.com/opengisch/QgisModelBakerLibrary/pull/80
> set transaction mode as enum

- QgisModelBaker/gui/panel/pg_config_panel.py
> Update schemas in separate task to avoid freezes

- QgisModelBaker/gui/panel/log_panel.py
- QgisModelBaker/gui/workflow_wizard/default_baskets_page.py
- QgisModelBaker/gui/workflow_wizard/execution_page.py
- QgisModelBaker/gui/workflow_wizard/import_schema_configuration_page.py
- QgisModelBaker/gui/workflow_wizard/project_creation_page.py
- QgisModelBaker/gui/workflow_wizard/workflow_wizard.py
- QgisModelBaker/ui/workflow_wizard/project_creation.ui
Since ili2db 4.11 the id of the metaconfiguration file used to create the physical database is stored in the meta-tables. This means, on **Project Creation** we consider this id and provide the linked **project topping**.
Still it's possible to **disable it** and choose another **project topping file**.
You can choose a **project topping file** (identified by model, db-type) from the **UsabILITy Hub** repositories or as well a YAML file from the **local system**.
... and not "metaconfiguration* file? 
Because on this step only project topping files are relevant. Metaconfiguration files are only relevant, when the schema is created. We thought about to provide them, to choose the same like on schema import, but this part is already provided by getting the topping from the DB.
Resolves #479 …
> Topping on create Project

- QgisModelBaker/gui/topping_wizard/additives_page.py
- QgisModelBaker/gui/topping_wizard/ili2dbsettings_page.py
- QgisModelBaker/gui/topping_wizard/layer_style_categories.py
- QgisModelBaker/gui/topping_wizard/layers_page.py
- QgisModelBaker/gui/topping_wizard/models_page.py
- QgisModelBaker/ui/topping_wizard/layer_style_categories.ui
- QgisModelBaker/utils/gui_utils.py
On going forward and back navigation in the wizard the checked states in...
- model page
- layer tree page
- additive settings (variables, print layouts etc)
... persists.
And a "select all" on categories...
Resolves #746
> Keep Settings in UsabILIty Exporter on Navigation

- QgisModelBaker/gui/workflow_wizard/workflow_wizard.py
- scripts/package_pip_packages.sh
We had the functionality where we wait in a loop for the topping files to be downloaded. When there is a local repository, we did not wait for download (because the files where already there). But the model (where the mapping from id to file location is done) was sometimes not refreshed yet. That's why we wait for the signal in every case now.
And I renamed the signal in the library to avoid confusion.
> Wait for model refresh on local repository topping receive

- QgisModelBaker/gui/workflow_wizard/project_creation_page.py
Apparently the lambda call leaded to a delay.
After some research I found out, that it anyway makes sense when we pass the signal argument directly (the rows of found toppings). If 0 then false and if >0 then true. All good...
> Fix python error wrapped C/C++ object of type xy has been deleted

- QgisModelBaker/gui/panel/pg_config_panel.py
**What is changed**
When opening the dialog, if there is a service stored in QSettings, we set it in the first place (before it was set in the last place), and after that we check for QSettings that complement the PG service settings.
**Other details**
Note the current PG service definition will take precedence over corresponding stored QSettings.
Also note that SSLMode is not being stored in QSettings (see https://github.com/opengisch/QgisModelBakerLibrary/blob/412e60ccf4a0cf96432470c49d3eb725489626de/modelbaker/db_factory/pg_command_config_manager.py#L149-L173). 
[PR #96](https://github.com/opengisch/QgisModelBakerLibrary/pull/96) to the underlying lib fixes that.
-------------
Fix #709
> [gui] Remember previous settings when using a PG service

- QgisModelBaker/gui/workflow_wizard/project_creation_page.py
- docs/docs/background_info/extended_models_optimization.md
- docs/docs/user_guide/import_workflow.md
- docs/mkdocs.yml
Most is done in the backend, but in the strategy selection combobox only HIDE and NONE should be provided (no GROUP).
As well the texts should describe the use case with smart1.
With this it reads the smart-inheritance mapping that has been chosen for the current schema and updates the combobox accordingly.
Requires https://github.com/opengisch/QgisModelBakerLibrary/pull/93
> Smart 1 project optimization

- QgisModelBaker/tests/test_pgservice.py
- QgisModelBaker/tests/utils.py
As well as additional settings given by users like schema, ssl-mode and auth config.
Note:
Added a prefix on a test utility function to avoid the `SKIPPED (This is a utility function, not a test function)` notice when running tests.
Follow-up #918
> [tests] Test that PG service settings are remembered

- QgisModelBaker/gui/ili2db_options.py
- QgisModelBaker/gui/options.py
- QgisModelBaker/gui/panel/gpkg_config_panel.py
- QgisModelBaker/gui/panel/log_panel.py
- QgisModelBaker/gui/panel/mssql_config_panel.py
- QgisModelBaker/gui/panel/pg_config_panel.py
- QgisModelBaker/gui/panel/session_panel.py
- QgisModelBaker/gui/topping_wizard/generation_page.py
- QgisModelBaker/gui/topping_wizard/ili2dbsettings_page.py
- QgisModelBaker/gui/topping_wizard/layers_page.py
- QgisModelBaker/gui/topping_wizard/models_page.py
- QgisModelBaker/gui/topping_wizard/referencedata_page.py
- QgisModelBaker/gui/topping_wizard/target_page.py
- QgisModelBaker/gui/workflow_wizard/database_selection_page.py
- QgisModelBaker/gui/workflow_wizard/default_baskets_page.py
- QgisModelBaker/gui/workflow_wizard/execution_page.py
- QgisModelBaker/gui/workflow_wizard/export_data_configuration_page.py
- QgisModelBaker/gui/workflow_wizard/import_data_configuration_page.py
- QgisModelBaker/gui/workflow_wizard/import_schema_configuration_page.py
- QgisModelBaker/gui/workflow_wizard/project_creation_page.py
- QgisModelBaker/gui/workflow_wizard/tid_configuration_page.py
- QgisModelBaker/gui/workflow_wizard/workflow_wizard.py
- QgisModelBaker/utils/gui_utils.py
+ [x] Improve color definition for log texts, taking into account the current theme (palette) and adjusting some colors to work well on both environments light and dark.
+ [x] DB panels' input widgets: 
+ [x] Background color according to validator state.
+ [x] Topping wizard's structure preview now visible in night mode.
Requires https://github.com/opengisch/QgisModelBakerLibrary/pull/101
Screenshots of new look and feel (default theme added for reference):
Fix #568
> [ux] Improve night/dark theme mode

- QgisModelBaker/gui/dataset_manager.py
- QgisModelBaker/gui/topping_wizard/referencedata_page.py
- QgisModelBaker/gui/workflow_wizard/database_selection_page.py
- QgisModelBaker/gui/workflow_wizard/import_source_selection_page.py
- QgisModelBaker/gui/workflow_wizard/project_creation_page.py
- QgisModelBaker/gui/workflow_wizard/workflow_wizard.py
- QgisModelBaker/ui/dataset_manager.ui
Because you barely want to edit datasets on another datasource than the one you are currently using, Model Baker detects now automatically the source of your project (according to the selected layer). You cannot edit the datasource in the Dataset Manager anymore. We removed it because it leaded to confusion.
And what if my current layer is not a valid layer (e.g. a group or a WMS)?
> Then it goes through all the layers and takes the first valid one.
And what if I have no project opened at all? 
> Then it takes the last used connection (used anywhere - not only in Dataset Manager)
I like that with Model Baker the QGIS Window is still responsive. But we had to decide, what functions in Model Baker Window (Wizard or Dataset Manager) should be triggered on interactions in the QGIS Window. In …
> Consequent use of database settings in Export / Dataset Manager

- QgisModelBaker/gui/panel/layer_tids_panel.py
- QgisModelBaker/ui/basket_panel.ui
- QgisModelBaker/ui/layer_tids_panel.ui
The settings for unique and not-null constraint are now provided by the OID Manger.
This requires this https://github.com/opengisch/QgisModelBakerLibrary/pull/103 where it sets the constraints when an OID is defined in the model and it does not set it when no OID is defined.
> OID Manager settings for not-null and unique constraint

- QgisModelBaker/gui/panel/pg_config_panel.py
- docs/docs/background_info/catalogues.md
- docs/mkdocs.yml
- docs/requirements.txt
- scripts/package_pip_packages.sh
Catch the Exceptions from pgserviceparser when no service file availble or service not found.
> Fix exceptions on no service file found

- QgisModelBaker/gui/panel/gpkg_config_panel.py
- QgisModelBaker/gui/panel/mssql_config_panel.py
- QgisModelBaker/gui/panel/pg_config_panel.py
- requirements.txt
Apparently this leaded to issues. Not sure why. Seems older QGIS had the problem.
Fixes #945 and fixes #947
> Remove override decorator 

- QgisModelBaker/gui/panel/tid_configurator_panel.py
- QgisModelBaker/gui/tid_manager.py
> Show warning message in TID manager when OIDs cannot be found

- QgisModelBaker/gui/panel/pg_config_panel.py
- QgisModelBaker/utils/globals.py
Fix #905
----
Depends on https://github.com/opengisch/QgisModelBakerLibrary/pull/110
> [export] Hide superuser checkbox on PG export and make it possible to run PG export with authConfig and no superuser

- QgisModelBaker/gui/topping_wizard/layer_style_categories.py
- QgisModelBaker/gui/topping_wizard/layers_page.py
- QgisModelBaker/ui/topping_wizard/layer_style_categories.ui
And with newer QGIS use the exposed QGIS model and delegate to make it beautiful: 
Requires https://github.com/qgis/QGIS/pull/58729
> Topping Exporter: Consider the layer type for style categories

- QgisModelBaker/gui/dataset_manager.py
It was a leftover from the previous functionality where the users have to select the db type. Meanwhile it's recognized from the current projecr or - in this case - recreated from the last used connection (read from the settings) there we need the stored db type and read it then according to it.
It previously leaded to issues when using a PG but reading the setting from MSSQL (even if not installed)...
> Fix on DB Manager: Get db type from settings and read the settings accordingly

- QgisModelBaker/gui/workflow_wizard/project_creation_page.py
- QgisModelBaker/ui/workflow_wizard/project_creation.ui
- QgisModelBaker/utils/globals.py
- scripts/package_pip_packages.sh
Requires https://github.com/opengisch/QgisModelBakerLibrary/pull/113
Fix #402
> Add support for translated models

- QgisModelBaker/gui/ili2db_options.py
- QgisModelBaker/gui/workflow_wizard/import_schema_configuration_page.py
- QgisModelBaker/gui/workflow_wizard/project_creation_page.py
- QgisModelBaker/ui/ili2db_options.ui
- QgisModelBaker/ui/workflow_wizard/project_creation.ui
Otherwise the setting is invisible and the parameter is `false`
This does only work with a sufficient GDAL version \* Otherwise it's invisible and false.
Reading such a project does only work with a sufficient GDAL version \* If the schema has been created with the `gpkgMultiGeomPerTable` *and* it contains tables with multiple geometry columns, but the current **GDAL version is not sufficient**, we block the creation of a QGIS Project.
When we have a **sufficient** GDAL version \* we can create a QGIS project, but need to warn, that others reading this project might have trouble.
This functionality is not standardized and does only work with GDAL Version >= 3.8
Windows Builds have it since 3.36 but Ubuntu from the current repositories not yet.
When a schema is created with this parameter …
> Concern multiple geometries per GeoPackage Table Frontend

- QgisModelBaker/gui/workflow_wizard/project_creation_page.py
- QgisModelBaker/utils/gui_utils.py
- scripts/package_pip_packages.sh
In the language combobox. Because it should not find English from Units etc.
And if only one language is found it's disabled anyway and only provides the "original" language.
Requires https://github.com/opengisch/QgisModelBakerLibrary/pull/117
> Pass blacklisted models to find available language because they are irrelevant

- QgisModelBaker/ui/workflow_wizard/default_baskets.ui
> improve usability of basket page with desciptive text 

- QgisModelBaker/gui/topping_wizard/additives_page.py
- QgisModelBaker/ui/topping_wizard/additives.ui
- scripts/package_pip_packages.sh
Since quite some time we are able to store the path to the validation configuration file as project variable, so we have it always in the validator:
This variable could be exported so far to the project topping **but** if the file is not stored on a accessible drive the project using this topping could not access to it.
That's why with this PR you have the option in the **Topping Exporter** to *create* a topping file from the variable with the name "validator_config" that is stored at the topping files.
Means we have now the validation-config.ini file in the toppings and link over the variable to the `ilidata:` key.
But what happens on project create with this topping?
Nothing :-) It keeps the `ilidata:` key in the variable. This means in the Validator we see the `ilidata:` key as well. …
> Export ValidationConfig File as Topping

- QgisModelBaker/gui/workflow_wizard/project_creation_page.py
- QgisModelBaker/qgismodelbaker.py
> Set default transaction mode for GPKG to AutomaticGroups (QGIS >= 3.26)

- QgisModelBaker/gui/panel/pg_config_panel.py
- QgisModelBaker/gui/workflow_wizard/database_selection_page.py
- QgisModelBaker/ui/dbparam_map.ui
- QgisModelBaker/ui/pg_settings_panel.ui
- scripts/package_pip_packages.sh
Specific user defined parameters are passed to ili2db via a temporary file to` --dbparams`. These settings are used to create or update a database. They are not considered in the QGIS project.
The possible parameters are described in the respective JDBC driver - I linked it to the description in the GUI: https://jdbc.postgresql.org/documentation/use/#connection-parameters
The dialog can be opened by the button "Specific custom parameters".
This is the dialog to set the parameters.
These parameters are stored in the configuration. Then on calling ili2pg they are written to a temporary file (like the sslmode).
This depends on https://github.com/opengisch/QgisModelBakerLibrary/pull/145
Resolves #1023
> Add --dbparams dialog in PG settings

- QgisModelBaker/gui/validate.py
- docs/docs/user_guide/validation.md
While evaluating this #1045 I noted again that the "fixed" entries in the list with this green button are hard to see. Maybe it's because of my color-blindness but even then, it's better to have it clearer.
And name it "mark as fixed" and not "set to fixed" to avoid that the user believes they really *fix* the error.
> Validator crossed and grayed out when error is marked as fixed

- QgisModelBaker/gui/panel/set_sequence_panel.py
- QgisModelBaker/gui/panel/tid_configurator_panel.py
- QgisModelBaker/gui/workflow_wizard/tid_configuration_page.py
- QgisModelBaker/ui/workflow_wizard/tid_configuration.ui
Remove "Set configuration" and progress bar. On "Finish" it performs the action. If there is an issue, it does not close the dialog and prints a message. On success, it closes the wizard. Mostly an issue encounters when something with the sequence happens.
Including fix, that it does not perform the sequence modification when the checkbox is not checked.
> Remove confusing "Set configuration" from OID Generation page

- QgisModelBaker/gui/panel/session_panel.py
- QgisModelBaker/gui/workflow_wizard/execution_page.py
When a session is skipped the loop to excecute all sessions is interupted.
On pressing 'run all commands' again only the one that are not done or skipped are started.
[Screencast from 29.08.2025 13:29:57.webm](https://github.com/user-attachments/assets/29bf5a6d-9390-450f-bbe7-8aa482863611)
This fixes #1021
> Fix weird behavior on failed ili2db sessions
